// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stationssvc.proto

package stsgrpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Station struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Timezone             string   `protobuf:"bytes,3,opt,name=timezone,proto3" json:"timezone,omitempty"`
	SourceType           string   `protobuf:"bytes,4,opt,name=sourceType,proto3" json:"sourceType,omitempty"`
	SourceId             string   `protobuf:"bytes,5,opt,name=sourceId,proto3" json:"sourceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Station) Reset()         { *m = Station{} }
func (m *Station) String() string { return proto.CompactTextString(m) }
func (*Station) ProtoMessage()    {}
func (*Station) Descriptor() ([]byte, []int) {
	return fileDescriptor_stationssvc_911a1da64d3cca8b, []int{0}
}
func (m *Station) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Station.Unmarshal(m, b)
}
func (m *Station) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Station.Marshal(b, m, deterministic)
}
func (dst *Station) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Station.Merge(dst, src)
}
func (m *Station) XXX_Size() int {
	return xxx_messageInfo_Station.Size(m)
}
func (m *Station) XXX_DiscardUnknown() {
	xxx_messageInfo_Station.DiscardUnknown(m)
}

var xxx_messageInfo_Station proto.InternalMessageInfo

func (m *Station) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Station) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Station) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

func (m *Station) GetSourceType() string {
	if m != nil {
		return m.SourceType
	}
	return ""
}

func (m *Station) GetSourceId() string {
	if m != nil {
		return m.SourceId
	}
	return ""
}

type GetStationsRequest struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStationsRequest) Reset()         { *m = GetStationsRequest{} }
func (m *GetStationsRequest) String() string { return proto.CompactTextString(m) }
func (*GetStationsRequest) ProtoMessage()    {}
func (*GetStationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_stationssvc_911a1da64d3cca8b, []int{1}
}
func (m *GetStationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStationsRequest.Unmarshal(m, b)
}
func (m *GetStationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStationsRequest.Marshal(b, m, deterministic)
}
func (dst *GetStationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStationsRequest.Merge(dst, src)
}
func (m *GetStationsRequest) XXX_Size() int {
	return xxx_messageInfo_GetStationsRequest.Size(m)
}
func (m *GetStationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStationsRequest proto.InternalMessageInfo

func (m *GetStationsRequest) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type GetStationsResponse struct {
	Sts                  map[string]*Station `protobuf:"bytes,1,rep,name=sts,proto3" json:"sts,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Err                  string              `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetStationsResponse) Reset()         { *m = GetStationsResponse{} }
func (m *GetStationsResponse) String() string { return proto.CompactTextString(m) }
func (*GetStationsResponse) ProtoMessage()    {}
func (*GetStationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_stationssvc_911a1da64d3cca8b, []int{2}
}
func (m *GetStationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStationsResponse.Unmarshal(m, b)
}
func (m *GetStationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStationsResponse.Marshal(b, m, deterministic)
}
func (dst *GetStationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStationsResponse.Merge(dst, src)
}
func (m *GetStationsResponse) XXX_Size() int {
	return xxx_messageInfo_GetStationsResponse.Size(m)
}
func (m *GetStationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStationsResponse proto.InternalMessageInfo

func (m *GetStationsResponse) GetSts() map[string]*Station {
	if m != nil {
		return m.Sts
	}
	return nil
}

func (m *GetStationsResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type GetAllStationsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllStationsRequest) Reset()         { *m = GetAllStationsRequest{} }
func (m *GetAllStationsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllStationsRequest) ProtoMessage()    {}
func (*GetAllStationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_stationssvc_911a1da64d3cca8b, []int{3}
}
func (m *GetAllStationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllStationsRequest.Unmarshal(m, b)
}
func (m *GetAllStationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllStationsRequest.Marshal(b, m, deterministic)
}
func (dst *GetAllStationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllStationsRequest.Merge(dst, src)
}
func (m *GetAllStationsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllStationsRequest.Size(m)
}
func (m *GetAllStationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllStationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllStationsRequest proto.InternalMessageInfo

type GetAllStationsResponse struct {
	Sts                  map[string]*Station `protobuf:"bytes,1,rep,name=sts,proto3" json:"sts,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Err                  string              `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetAllStationsResponse) Reset()         { *m = GetAllStationsResponse{} }
func (m *GetAllStationsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllStationsResponse) ProtoMessage()    {}
func (*GetAllStationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_stationssvc_911a1da64d3cca8b, []int{4}
}
func (m *GetAllStationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllStationsResponse.Unmarshal(m, b)
}
func (m *GetAllStationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllStationsResponse.Marshal(b, m, deterministic)
}
func (dst *GetAllStationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllStationsResponse.Merge(dst, src)
}
func (m *GetAllStationsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllStationsResponse.Size(m)
}
func (m *GetAllStationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllStationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllStationsResponse proto.InternalMessageInfo

func (m *GetAllStationsResponse) GetSts() map[string]*Station {
	if m != nil {
		return m.Sts
	}
	return nil
}

func (m *GetAllStationsResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type GetStationsBySrcTypeRequest struct {
	Types                []string `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStationsBySrcTypeRequest) Reset()         { *m = GetStationsBySrcTypeRequest{} }
func (m *GetStationsBySrcTypeRequest) String() string { return proto.CompactTextString(m) }
func (*GetStationsBySrcTypeRequest) ProtoMessage()    {}
func (*GetStationsBySrcTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_stationssvc_911a1da64d3cca8b, []int{5}
}
func (m *GetStationsBySrcTypeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStationsBySrcTypeRequest.Unmarshal(m, b)
}
func (m *GetStationsBySrcTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStationsBySrcTypeRequest.Marshal(b, m, deterministic)
}
func (dst *GetStationsBySrcTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStationsBySrcTypeRequest.Merge(dst, src)
}
func (m *GetStationsBySrcTypeRequest) XXX_Size() int {
	return xxx_messageInfo_GetStationsBySrcTypeRequest.Size(m)
}
func (m *GetStationsBySrcTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStationsBySrcTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStationsBySrcTypeRequest proto.InternalMessageInfo

func (m *GetStationsBySrcTypeRequest) GetTypes() []string {
	if m != nil {
		return m.Types
	}
	return nil
}

type GetStationsBySrcTypeResponse struct {
	Sts                  map[string]*Station `protobuf:"bytes,1,rep,name=sts,proto3" json:"sts,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Err                  string              `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetStationsBySrcTypeResponse) Reset()         { *m = GetStationsBySrcTypeResponse{} }
func (m *GetStationsBySrcTypeResponse) String() string { return proto.CompactTextString(m) }
func (*GetStationsBySrcTypeResponse) ProtoMessage()    {}
func (*GetStationsBySrcTypeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_stationssvc_911a1da64d3cca8b, []int{6}
}
func (m *GetStationsBySrcTypeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStationsBySrcTypeResponse.Unmarshal(m, b)
}
func (m *GetStationsBySrcTypeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStationsBySrcTypeResponse.Marshal(b, m, deterministic)
}
func (dst *GetStationsBySrcTypeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStationsBySrcTypeResponse.Merge(dst, src)
}
func (m *GetStationsBySrcTypeResponse) XXX_Size() int {
	return xxx_messageInfo_GetStationsBySrcTypeResponse.Size(m)
}
func (m *GetStationsBySrcTypeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStationsBySrcTypeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStationsBySrcTypeResponse proto.InternalMessageInfo

func (m *GetStationsBySrcTypeResponse) GetSts() map[string]*Station {
	if m != nil {
		return m.Sts
	}
	return nil
}

func (m *GetStationsBySrcTypeResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type AddStationsRequest struct {
	Sts                  []*Station `protobuf:"bytes,1,rep,name=sts,proto3" json:"sts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AddStationsRequest) Reset()         { *m = AddStationsRequest{} }
func (m *AddStationsRequest) String() string { return proto.CompactTextString(m) }
func (*AddStationsRequest) ProtoMessage()    {}
func (*AddStationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_stationssvc_911a1da64d3cca8b, []int{7}
}
func (m *AddStationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddStationsRequest.Unmarshal(m, b)
}
func (m *AddStationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddStationsRequest.Marshal(b, m, deterministic)
}
func (dst *AddStationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddStationsRequest.Merge(dst, src)
}
func (m *AddStationsRequest) XXX_Size() int {
	return xxx_messageInfo_AddStationsRequest.Size(m)
}
func (m *AddStationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddStationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddStationsRequest proto.InternalMessageInfo

func (m *AddStationsRequest) GetSts() []*Station {
	if m != nil {
		return m.Sts
	}
	return nil
}

type AddStationsResponse struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddStationsResponse) Reset()         { *m = AddStationsResponse{} }
func (m *AddStationsResponse) String() string { return proto.CompactTextString(m) }
func (*AddStationsResponse) ProtoMessage()    {}
func (*AddStationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_stationssvc_911a1da64d3cca8b, []int{8}
}
func (m *AddStationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddStationsResponse.Unmarshal(m, b)
}
func (m *AddStationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddStationsResponse.Marshal(b, m, deterministic)
}
func (dst *AddStationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddStationsResponse.Merge(dst, src)
}
func (m *AddStationsResponse) XXX_Size() int {
	return xxx_messageInfo_AddStationsResponse.Size(m)
}
func (m *AddStationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddStationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddStationsResponse proto.InternalMessageInfo

func (m *AddStationsResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*Station)(nil), "stsgrpc.Station")
	proto.RegisterType((*GetStationsRequest)(nil), "stsgrpc.GetStationsRequest")
	proto.RegisterType((*GetStationsResponse)(nil), "stsgrpc.GetStationsResponse")
	proto.RegisterMapType((map[string]*Station)(nil), "stsgrpc.GetStationsResponse.StsEntry")
	proto.RegisterType((*GetAllStationsRequest)(nil), "stsgrpc.GetAllStationsRequest")
	proto.RegisterType((*GetAllStationsResponse)(nil), "stsgrpc.GetAllStationsResponse")
	proto.RegisterMapType((map[string]*Station)(nil), "stsgrpc.GetAllStationsResponse.StsEntry")
	proto.RegisterType((*GetStationsBySrcTypeRequest)(nil), "stsgrpc.GetStationsBySrcTypeRequest")
	proto.RegisterType((*GetStationsBySrcTypeResponse)(nil), "stsgrpc.GetStationsBySrcTypeResponse")
	proto.RegisterMapType((map[string]*Station)(nil), "stsgrpc.GetStationsBySrcTypeResponse.StsEntry")
	proto.RegisterType((*AddStationsRequest)(nil), "stsgrpc.AddStationsRequest")
	proto.RegisterType((*AddStationsResponse)(nil), "stsgrpc.AddStationsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StationSVCClient is the client API for StationSVC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StationSVCClient interface {
	GetStations(ctx context.Context, in *GetStationsRequest, opts ...grpc.CallOption) (*GetStationsResponse, error)
	GetAllStations(ctx context.Context, in *GetAllStationsRequest, opts ...grpc.CallOption) (*GetAllStationsResponse, error)
	GetStationsBySrcType(ctx context.Context, in *GetStationsBySrcTypeRequest, opts ...grpc.CallOption) (*GetStationsBySrcTypeResponse, error)
	AddStations(ctx context.Context, in *AddStationsRequest, opts ...grpc.CallOption) (*AddStationsResponse, error)
}

type stationSVCClient struct {
	cc *grpc.ClientConn
}

func NewStationSVCClient(cc *grpc.ClientConn) StationSVCClient {
	return &stationSVCClient{cc}
}

func (c *stationSVCClient) GetStations(ctx context.Context, in *GetStationsRequest, opts ...grpc.CallOption) (*GetStationsResponse, error) {
	out := new(GetStationsResponse)
	err := c.cc.Invoke(ctx, "/stsgrpc.StationSVC/GetStations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stationSVCClient) GetAllStations(ctx context.Context, in *GetAllStationsRequest, opts ...grpc.CallOption) (*GetAllStationsResponse, error) {
	out := new(GetAllStationsResponse)
	err := c.cc.Invoke(ctx, "/stsgrpc.StationSVC/GetAllStations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stationSVCClient) GetStationsBySrcType(ctx context.Context, in *GetStationsBySrcTypeRequest, opts ...grpc.CallOption) (*GetStationsBySrcTypeResponse, error) {
	out := new(GetStationsBySrcTypeResponse)
	err := c.cc.Invoke(ctx, "/stsgrpc.StationSVC/GetStationsBySrcType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stationSVCClient) AddStations(ctx context.Context, in *AddStationsRequest, opts ...grpc.CallOption) (*AddStationsResponse, error) {
	out := new(AddStationsResponse)
	err := c.cc.Invoke(ctx, "/stsgrpc.StationSVC/AddStations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StationSVCServer is the server API for StationSVC service.
type StationSVCServer interface {
	GetStations(context.Context, *GetStationsRequest) (*GetStationsResponse, error)
	GetAllStations(context.Context, *GetAllStationsRequest) (*GetAllStationsResponse, error)
	GetStationsBySrcType(context.Context, *GetStationsBySrcTypeRequest) (*GetStationsBySrcTypeResponse, error)
	AddStations(context.Context, *AddStationsRequest) (*AddStationsResponse, error)
}

func RegisterStationSVCServer(s *grpc.Server, srv StationSVCServer) {
	s.RegisterService(&_StationSVC_serviceDesc, srv)
}

func _StationSVC_GetStations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StationSVCServer).GetStations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stsgrpc.StationSVC/GetStations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StationSVCServer).GetStations(ctx, req.(*GetStationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StationSVC_GetAllStations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllStationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StationSVCServer).GetAllStations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stsgrpc.StationSVC/GetAllStations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StationSVCServer).GetAllStations(ctx, req.(*GetAllStationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StationSVC_GetStationsBySrcType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStationsBySrcTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StationSVCServer).GetStationsBySrcType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stsgrpc.StationSVC/GetStationsBySrcType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StationSVCServer).GetStationsBySrcType(ctx, req.(*GetStationsBySrcTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StationSVC_AddStations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddStationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StationSVCServer).AddStations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stsgrpc.StationSVC/AddStations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StationSVCServer).AddStations(ctx, req.(*AddStationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StationSVC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stsgrpc.StationSVC",
	HandlerType: (*StationSVCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStations",
			Handler:    _StationSVC_GetStations_Handler,
		},
		{
			MethodName: "GetAllStations",
			Handler:    _StationSVC_GetAllStations_Handler,
		},
		{
			MethodName: "GetStationsBySrcType",
			Handler:    _StationSVC_GetStationsBySrcType_Handler,
		},
		{
			MethodName: "AddStations",
			Handler:    _StationSVC_AddStations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stationssvc.proto",
}

func init() { proto.RegisterFile("stationssvc.proto", fileDescriptor_stationssvc_911a1da64d3cca8b) }

var fileDescriptor_stationssvc_911a1da64d3cca8b = []byte{
	// 481 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0xf5, 0x23, 0xa1, 0xed, 0x8d, 0x54, 0x95, 0x5b, 0x28, 0x96, 0x5b, 0xb5, 0xd5, 0x88, 0x42,
	0x16, 0xe0, 0x4a, 0x61, 0x41, 0xe9, 0x8a, 0x16, 0xa1, 0x02, 0x4b, 0x1b, 0xb1, 0x4f, 0xec, 0x21,
	0x58, 0x24, 0x1e, 0xe3, 0x19, 0x57, 0x32, 0x7b, 0x7e, 0x86, 0x15, 0x1f, 0xc0, 0x07, 0xf0, 0x15,
	0x88, 0x4f, 0x41, 0xf3, 0x48, 0x34, 0x49, 0x0c, 0xed, 0x2a, 0xbb, 0xfb, 0x3a, 0x9e, 0x7b, 0xce,
	0xb9, 0x32, 0xdc, 0xe5, 0x62, 0x28, 0x72, 0x56, 0x70, 0x7e, 0x9d, 0x46, 0x65, 0xc5, 0x04, 0xc3,
	0x0d, 0x2e, 0xf8, 0xb8, 0x2a, 0xd3, 0xf0, 0xe9, 0x38, 0x17, 0x9f, 0xea, 0x51, 0x94, 0xb2, 0xe9,
	0xe9, 0x98, 0x8d, 0xd9, 0xa9, 0xea, 0x8f, 0xea, 0x8f, 0x2a, 0x53, 0x89, 0x8a, 0x34, 0x8e, 0x7c,
	0x73, 0x61, 0x23, 0xd1, 0x5f, 0xc3, 0x6d, 0xf0, 0xf2, 0x2c, 0x70, 0x8f, 0xdd, 0xfe, 0x56, 0xec,
	0xe5, 0x19, 0x22, 0x74, 0x8a, 0xe1, 0x94, 0x06, 0x9e, 0xaa, 0xa8, 0x18, 0x43, 0xd8, 0x14, 0xf9,
	0x94, 0x7e, 0x65, 0x05, 0x0d, 0x7c, 0x55, 0x9f, 0xe7, 0x78, 0x08, 0xc0, 0x59, 0x5d, 0xa5, 0xf4,
	0x7d, 0x53, 0xd2, 0xa0, 0xa3, 0xba, 0x56, 0x45, 0x62, 0x75, 0xf6, 0x36, 0x0b, 0xba, 0x1a, 0x3b,
	0xcb, 0xc9, 0x13, 0xc0, 0x2b, 0x2a, 0xcc, 0x26, 0x3c, 0xa6, 0x5f, 0x6a, 0xca, 0x05, 0xee, 0x81,
	0x9f, 0x67, 0x3c, 0x70, 0x8f, 0xfd, 0xfe, 0xd6, 0x65, 0xe7, 0xd7, 0xef, 0x23, 0x27, 0x96, 0x05,
	0xf2, 0xdd, 0x85, 0xdd, 0x85, 0x71, 0x5e, 0xb2, 0x82, 0x53, 0x7c, 0x0e, 0x3e, 0x17, 0x7a, 0xbe,
	0x37, 0x38, 0x89, 0x8c, 0x26, 0x51, 0xcb, 0x68, 0x94, 0x08, 0xfe, 0xba, 0x10, 0x55, 0x13, 0x4b,
	0x04, 0xee, 0x80, 0x4f, 0xab, 0xca, 0x30, 0x95, 0x61, 0xf8, 0x06, 0x36, 0x67, 0x23, 0xb2, 0xfb,
	0x99, 0x36, 0x46, 0x19, 0x19, 0xe2, 0x23, 0xe8, 0x5e, 0x0f, 0x27, 0xb5, 0xd6, 0xa6, 0x37, 0xd8,
	0x99, 0x3f, 0x65, 0xde, 0x89, 0x75, 0xfb, 0xdc, 0x3b, 0x73, 0xc9, 0x03, 0xb8, 0x7f, 0x45, 0xc5,
	0xc5, 0x64, 0xb2, 0xc4, 0x8e, 0xfc, 0x70, 0x61, 0x6f, 0xb9, 0x63, 0x88, 0x9c, 0xdb, 0x44, 0xfa,
	0x36, 0x91, 0x96, 0xe9, 0x35, 0x72, 0x79, 0x01, 0xfb, 0x96, 0x98, 0x97, 0x4d, 0x52, 0xa5, 0xd2,
	0xda, 0x99, 0x5f, 0x21, 0x74, 0x45, 0x53, 0xd2, 0x45, 0xc7, 0x74, 0x89, 0xfc, 0x74, 0xe1, 0xa0,
	0x1d, 0x6b, 0x38, 0xbf, 0xb4, 0x39, 0x47, 0x6d, 0xe6, 0xad, 0x60, 0xd6, 0xc8, 0xfc, 0x0c, 0xf0,
	0x22, 0xcb, 0x96, 0x0f, 0x94, 0xd8, 0x3b, 0xaf, 0xe2, 0x65, 0x93, 0x3c, 0x86, 0xdd, 0x05, 0xa4,
	0xa1, 0x6b, 0x96, 0x75, 0xe7, 0xcb, 0x0e, 0xfe, 0x78, 0x00, 0x66, 0x2c, 0xf9, 0xf0, 0x0a, 0xdf,
	0x41, 0xcf, 0xe2, 0x8e, 0xfb, 0xed, 0xe7, 0xac, 0xf6, 0x08, 0x0f, 0xfe, 0x77, 0xeb, 0xc4, 0xc1,
	0x04, 0xb6, 0x17, 0x6f, 0x07, 0x0f, 0xff, 0x79, 0x54, 0xfa, 0x8b, 0x47, 0x37, 0x1c, 0x1d, 0x71,
	0x90, 0xc2, 0xbd, 0x36, 0x73, 0xf0, 0xe1, 0x0d, 0xde, 0xe9, 0x07, 0x4e, 0x6e, 0xe5, 0x30, 0x71,
	0xa4, 0x0e, 0x96, 0x7e, 0x96, 0x0e, 0xab, 0x7e, 0x58, 0x3a, 0xb4, 0x48, 0x4e, 0x9c, 0xd1, 0x1d,
	0xf5, 0xd7, 0x7b, 0xf6, 0x37, 0x00, 0x00, 0xff, 0xff, 0x72, 0x30, 0x99, 0xb6, 0x42, 0x05, 0x00,
	0x00,
}
