// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.17.3
// source: daydegreesvc.proto

package ddgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Params struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Station   string  `protobuf:"bytes,1,opt,name=Station,proto3" json:"Station,omitempty"`
	Start     string  `protobuf:"bytes,2,opt,name=Start,proto3" json:"Start,omitempty"`
	End       string  `protobuf:"bytes,3,opt,name=End,proto3" json:"End,omitempty"`
	Breakdown string  `protobuf:"bytes,4,opt,name=Breakdown,proto3" json:"Breakdown,omitempty"`
	Tb        float64 `protobuf:"fixed64,5,opt,name=Tb,proto3" json:"Tb,omitempty"`
	Tr        float64 `protobuf:"fixed64,6,opt,name=Tr,proto3" json:"Tr,omitempty"`
	Method    string  `protobuf:"bytes,7,opt,name=Method,proto3" json:"Method,omitempty"`
	DayCalc   string  `protobuf:"bytes,8,opt,name=DayCalc,proto3" json:"DayCalc,omitempty"`
	WeekStart int32   `protobuf:"varint,9,opt,name=WeekStart,proto3" json:"WeekStart,omitempty"`
	Metric    bool    `protobuf:"varint,10,opt,name=Metric,proto3" json:"Metric,omitempty"`
}

func (x *Params) Reset() {
	*x = Params{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daydegreesvc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Params) ProtoMessage() {}

func (x *Params) ProtoReflect() protoreflect.Message {
	mi := &file_daydegreesvc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Params.ProtoReflect.Descriptor instead.
func (*Params) Descriptor() ([]byte, []int) {
	return file_daydegreesvc_proto_rawDescGZIP(), []int{0}
}

func (x *Params) GetStation() string {
	if x != nil {
		return x.Station
	}
	return ""
}

func (x *Params) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *Params) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *Params) GetBreakdown() string {
	if x != nil {
		return x.Breakdown
	}
	return ""
}

func (x *Params) GetTb() float64 {
	if x != nil {
		return x.Tb
	}
	return 0
}

func (x *Params) GetTr() float64 {
	if x != nil {
		return x.Tr
	}
	return 0
}

func (x *Params) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Params) GetDayCalc() string {
	if x != nil {
		return x.DayCalc
	}
	return ""
}

func (x *Params) GetWeekStart() int32 {
	if x != nil {
		return x.WeekStart
	}
	return 0
}

func (x *Params) GetMetric() bool {
	if x != nil {
		return x.Metric
	}
	return false
}

type Degree struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date string  `protobuf:"bytes,1,opt,name=Date,proto3" json:"Date,omitempty"`
	Temp float64 `protobuf:"fixed64,2,opt,name=Temp,proto3" json:"Temp,omitempty"`
}

func (x *Degree) Reset() {
	*x = Degree{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daydegreesvc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Degree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Degree) ProtoMessage() {}

func (x *Degree) ProtoReflect() protoreflect.Message {
	mi := &file_daydegreesvc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Degree.ProtoReflect.Descriptor instead.
func (*Degree) Descriptor() ([]byte, []int) {
	return file_daydegreesvc_proto_rawDescGZIP(), []int{1}
}

func (x *Degree) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Degree) GetTemp() float64 {
	if x != nil {
		return x.Temp
	}
	return 0
}

type GetDegreeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Params *Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
}

func (x *GetDegreeRequest) Reset() {
	*x = GetDegreeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daydegreesvc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDegreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDegreeRequest) ProtoMessage() {}

func (x *GetDegreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daydegreesvc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDegreeRequest.ProtoReflect.Descriptor instead.
func (*GetDegreeRequest) Descriptor() ([]byte, []int) {
	return file_daydegreesvc_proto_rawDescGZIP(), []int{2}
}

func (x *GetDegreeRequest) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

type GetDegreeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Degrees []*Degree `protobuf:"bytes,1,rep,name=degrees,proto3" json:"degrees,omitempty"`
	Err     string    `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *GetDegreeResponse) Reset() {
	*x = GetDegreeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daydegreesvc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDegreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDegreeResponse) ProtoMessage() {}

func (x *GetDegreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daydegreesvc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDegreeResponse.ProtoReflect.Descriptor instead.
func (*GetDegreeResponse) Descriptor() ([]byte, []int) {
	return file_daydegreesvc_proto_rawDescGZIP(), []int{3}
}

func (x *GetDegreeResponse) GetDegrees() []*Degree {
	if x != nil {
		return x.Degrees
	}
	return nil
}

func (x *GetDegreeResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type GetAverageDegreeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Params *Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Years  int32   `protobuf:"varint,2,opt,name=Years,proto3" json:"Years,omitempty"`
}

func (x *GetAverageDegreeRequest) Reset() {
	*x = GetAverageDegreeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daydegreesvc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAverageDegreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAverageDegreeRequest) ProtoMessage() {}

func (x *GetAverageDegreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daydegreesvc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAverageDegreeRequest.ProtoReflect.Descriptor instead.
func (*GetAverageDegreeRequest) Descriptor() ([]byte, []int) {
	return file_daydegreesvc_proto_rawDescGZIP(), []int{4}
}

func (x *GetAverageDegreeRequest) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *GetAverageDegreeRequest) GetYears() int32 {
	if x != nil {
		return x.Years
	}
	return 0
}

type GetAverageDegreeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Degrees []*Degree `protobuf:"bytes,1,rep,name=degrees,proto3" json:"degrees,omitempty"`
	Err     string    `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *GetAverageDegreeResponse) Reset() {
	*x = GetAverageDegreeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daydegreesvc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAverageDegreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAverageDegreeResponse) ProtoMessage() {}

func (x *GetAverageDegreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daydegreesvc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAverageDegreeResponse.ProtoReflect.Descriptor instead.
func (*GetAverageDegreeResponse) Descriptor() ([]byte, []int) {
	return file_daydegreesvc_proto_rawDescGZIP(), []int{5}
}

func (x *GetAverageDegreeResponse) GetDegrees() []*Degree {
	if x != nil {
		return x.Degrees
	}
	return nil
}

func (x *GetAverageDegreeResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_daydegreesvc_proto protoreflect.FileDescriptor

var file_daydegreesvc_proto_rawDesc = []byte{
	0x0a, 0x12, 0x64, 0x61, 0x79, 0x64, 0x65, 0x67, 0x72, 0x65, 0x65, 0x73, 0x76, 0x63, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x64, 0x64, 0x67, 0x72, 0x70, 0x63, 0x22, 0xf0, 0x01, 0x0a,
	0x06, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x6e, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x45, 0x6e, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x72, 0x65,
	0x61, 0x6b, 0x64, 0x6f, 0x77, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x42, 0x72,
	0x65, 0x61, 0x6b, 0x64, 0x6f, 0x77, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x54, 0x62, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x02, 0x54, 0x62, 0x12, 0x0e, 0x0a, 0x02, 0x54, 0x72, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x02, 0x54, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x44, 0x61, 0x79, 0x43, 0x61, 0x6c, 0x63, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x44, 0x61, 0x79, 0x43, 0x61, 0x6c, 0x63, 0x12, 0x1c, 0x0a, 0x09, 0x57, 0x65, 0x65,
	0x6b, 0x53, 0x74, 0x61, 0x72, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x57, 0x65,
	0x65, 0x6b, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x22,
	0x30, 0x0a, 0x06, 0x44, 0x65, 0x67, 0x72, 0x65, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x54, 0x65, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x54, 0x65, 0x6d,
	0x70, 0x22, 0x3a, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x44, 0x65, 0x67, 0x72, 0x65, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x64, 0x64, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x4f, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x44, 0x65, 0x67, 0x72, 0x65, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x64, 0x65, 0x67, 0x72, 0x65, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x64, 0x64, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x65, 0x67,
	0x72, 0x65, 0x65, 0x52, 0x07, 0x64, 0x65, 0x67, 0x72, 0x65, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x22, 0x57,
	0x0a, 0x17, 0x47, 0x65, 0x74, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x44, 0x65, 0x67, 0x72,
	0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x06, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x64, 0x64, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x59, 0x65, 0x61, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x59, 0x65, 0x61, 0x72, 0x73, 0x22, 0x56, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x41, 0x76,
	0x65, 0x72, 0x61, 0x67, 0x65, 0x44, 0x65, 0x67, 0x72, 0x65, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x64, 0x65, 0x67, 0x72, 0x65, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x64, 0x64, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x65,
	0x67, 0x72, 0x65, 0x65, 0x52, 0x07, 0x64, 0x65, 0x67, 0x72, 0x65, 0x65, 0x73, 0x12, 0x10, 0x0a,
	0x03, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x32,
	0xab, 0x01, 0x0a, 0x0c, 0x44, 0x61, 0x79, 0x44, 0x65, 0x67, 0x72, 0x65, 0x65, 0x53, 0x56, 0x43,
	0x12, 0x42, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x44, 0x65, 0x67, 0x72, 0x65, 0x65, 0x12, 0x18, 0x2e,
	0x64, 0x64, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x67, 0x72, 0x65, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x64, 0x64, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x67, 0x72, 0x65, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x76, 0x65, 0x72, 0x61,
	0x67, 0x65, 0x44, 0x65, 0x67, 0x72, 0x65, 0x65, 0x12, 0x1f, 0x2e, 0x64, 0x64, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x44, 0x65, 0x67, 0x72,
	0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x64, 0x64, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x44, 0x65, 0x67,
	0x72, 0x65, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x36, 0x5a,
	0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x6c, 0x61, 0x73,
	0x68, 0x65, 0x72, 0x75, 0x70, 0x2f, 0x67, 0x72, 0x61, 0x64, 0x74, 0x61, 0x67, 0x65, 0x2e, 0x64,
	0x65, 0x2f, 0x64, 0x61, 0x79, 0x64, 0x65, 0x67, 0x72, 0x65, 0x65, 0x73, 0x76, 0x63, 0x2f, 0x64,
	0x64, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_daydegreesvc_proto_rawDescOnce sync.Once
	file_daydegreesvc_proto_rawDescData = file_daydegreesvc_proto_rawDesc
)

func file_daydegreesvc_proto_rawDescGZIP() []byte {
	file_daydegreesvc_proto_rawDescOnce.Do(func() {
		file_daydegreesvc_proto_rawDescData = protoimpl.X.CompressGZIP(file_daydegreesvc_proto_rawDescData)
	})
	return file_daydegreesvc_proto_rawDescData
}

var file_daydegreesvc_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_daydegreesvc_proto_goTypes = []any{
	(*Params)(nil),                   // 0: ddgrpc.Params
	(*Degree)(nil),                   // 1: ddgrpc.Degree
	(*GetDegreeRequest)(nil),         // 2: ddgrpc.GetDegreeRequest
	(*GetDegreeResponse)(nil),        // 3: ddgrpc.GetDegreeResponse
	(*GetAverageDegreeRequest)(nil),  // 4: ddgrpc.GetAverageDegreeRequest
	(*GetAverageDegreeResponse)(nil), // 5: ddgrpc.GetAverageDegreeResponse
}
var file_daydegreesvc_proto_depIdxs = []int32{
	0, // 0: ddgrpc.GetDegreeRequest.params:type_name -> ddgrpc.Params
	1, // 1: ddgrpc.GetDegreeResponse.degrees:type_name -> ddgrpc.Degree
	0, // 2: ddgrpc.GetAverageDegreeRequest.params:type_name -> ddgrpc.Params
	1, // 3: ddgrpc.GetAverageDegreeResponse.degrees:type_name -> ddgrpc.Degree
	2, // 4: ddgrpc.DayDegreeSVC.GetDegree:input_type -> ddgrpc.GetDegreeRequest
	4, // 5: ddgrpc.DayDegreeSVC.GetAverageDegree:input_type -> ddgrpc.GetAverageDegreeRequest
	3, // 6: ddgrpc.DayDegreeSVC.GetDegree:output_type -> ddgrpc.GetDegreeResponse
	5, // 7: ddgrpc.DayDegreeSVC.GetAverageDegree:output_type -> ddgrpc.GetAverageDegreeResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_daydegreesvc_proto_init() }
func file_daydegreesvc_proto_init() {
	if File_daydegreesvc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_daydegreesvc_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Params); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daydegreesvc_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Degree); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daydegreesvc_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetDegreeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daydegreesvc_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetDegreeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daydegreesvc_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetAverageDegreeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daydegreesvc_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetAverageDegreeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_daydegreesvc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_daydegreesvc_proto_goTypes,
		DependencyIndexes: file_daydegreesvc_proto_depIdxs,
		MessageInfos:      file_daydegreesvc_proto_msgTypes,
	}.Build()
	File_daydegreesvc_proto = out.File
	file_daydegreesvc_proto_rawDesc = nil
	file_daydegreesvc_proto_goTypes = nil
	file_daydegreesvc_proto_depIdxs = nil
}
