// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hourlysvc.proto

package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Temperature struct {
	Date                 string   `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Temperature          float32  `protobuf:"fixed32,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Temperature) Reset()         { *m = Temperature{} }
func (m *Temperature) String() string { return proto.CompactTextString(m) }
func (*Temperature) ProtoMessage()    {}
func (*Temperature) Descriptor() ([]byte, []int) {
	return fileDescriptor_hourlysvc_a575eba4ac5e16d2, []int{0}
}
func (m *Temperature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Temperature.Unmarshal(m, b)
}
func (m *Temperature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Temperature.Marshal(b, m, deterministic)
}
func (dst *Temperature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Temperature.Merge(dst, src)
}
func (m *Temperature) XXX_Size() int {
	return xxx_messageInfo_Temperature.Size(m)
}
func (m *Temperature) XXX_DiscardUnknown() {
	xxx_messageInfo_Temperature.DiscardUnknown(m)
}

var xxx_messageInfo_Temperature proto.InternalMessageInfo

func (m *Temperature) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *Temperature) GetTemperature() float32 {
	if m != nil {
		return m.Temperature
	}
	return 0
}

type GetPeriodRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Start                string   `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End                  string   `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPeriodRequest) Reset()         { *m = GetPeriodRequest{} }
func (m *GetPeriodRequest) String() string { return proto.CompactTextString(m) }
func (*GetPeriodRequest) ProtoMessage()    {}
func (*GetPeriodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hourlysvc_a575eba4ac5e16d2, []int{1}
}
func (m *GetPeriodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPeriodRequest.Unmarshal(m, b)
}
func (m *GetPeriodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPeriodRequest.Marshal(b, m, deterministic)
}
func (dst *GetPeriodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPeriodRequest.Merge(dst, src)
}
func (m *GetPeriodRequest) XXX_Size() int {
	return xxx_messageInfo_GetPeriodRequest.Size(m)
}
func (m *GetPeriodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPeriodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPeriodRequest proto.InternalMessageInfo

func (m *GetPeriodRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetPeriodRequest) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *GetPeriodRequest) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

type GetPeriodResponse struct {
	Temps                []*Temperature `protobuf:"bytes,1,rep,name=temps,proto3" json:"temps,omitempty"`
	Err                  string         `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetPeriodResponse) Reset()         { *m = GetPeriodResponse{} }
func (m *GetPeriodResponse) String() string { return proto.CompactTextString(m) }
func (*GetPeriodResponse) ProtoMessage()    {}
func (*GetPeriodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_hourlysvc_a575eba4ac5e16d2, []int{2}
}
func (m *GetPeriodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPeriodResponse.Unmarshal(m, b)
}
func (m *GetPeriodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPeriodResponse.Marshal(b, m, deterministic)
}
func (dst *GetPeriodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPeriodResponse.Merge(dst, src)
}
func (m *GetPeriodResponse) XXX_Size() int {
	return xxx_messageInfo_GetPeriodResponse.Size(m)
}
func (m *GetPeriodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPeriodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPeriodResponse proto.InternalMessageInfo

func (m *GetPeriodResponse) GetTemps() []*Temperature {
	if m != nil {
		return m.Temps
	}
	return nil
}

func (m *GetPeriodResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type PushPeriodRequest struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Temps                []*Temperature `protobuf:"bytes,2,rep,name=temps,proto3" json:"temps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PushPeriodRequest) Reset()         { *m = PushPeriodRequest{} }
func (m *PushPeriodRequest) String() string { return proto.CompactTextString(m) }
func (*PushPeriodRequest) ProtoMessage()    {}
func (*PushPeriodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hourlysvc_a575eba4ac5e16d2, []int{3}
}
func (m *PushPeriodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushPeriodRequest.Unmarshal(m, b)
}
func (m *PushPeriodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushPeriodRequest.Marshal(b, m, deterministic)
}
func (dst *PushPeriodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushPeriodRequest.Merge(dst, src)
}
func (m *PushPeriodRequest) XXX_Size() int {
	return xxx_messageInfo_PushPeriodRequest.Size(m)
}
func (m *PushPeriodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushPeriodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushPeriodRequest proto.InternalMessageInfo

func (m *PushPeriodRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PushPeriodRequest) GetTemps() []*Temperature {
	if m != nil {
		return m.Temps
	}
	return nil
}

type PushPeriodResponse struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushPeriodResponse) Reset()         { *m = PushPeriodResponse{} }
func (m *PushPeriodResponse) String() string { return proto.CompactTextString(m) }
func (*PushPeriodResponse) ProtoMessage()    {}
func (*PushPeriodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_hourlysvc_a575eba4ac5e16d2, []int{4}
}
func (m *PushPeriodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushPeriodResponse.Unmarshal(m, b)
}
func (m *PushPeriodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushPeriodResponse.Marshal(b, m, deterministic)
}
func (dst *PushPeriodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushPeriodResponse.Merge(dst, src)
}
func (m *PushPeriodResponse) XXX_Size() int {
	return xxx_messageInfo_PushPeriodResponse.Size(m)
}
func (m *PushPeriodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PushPeriodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PushPeriodResponse proto.InternalMessageInfo

func (m *PushPeriodResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type GetUpdateDateRequest struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUpdateDateRequest) Reset()         { *m = GetUpdateDateRequest{} }
func (m *GetUpdateDateRequest) String() string { return proto.CompactTextString(m) }
func (*GetUpdateDateRequest) ProtoMessage()    {}
func (*GetUpdateDateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hourlysvc_a575eba4ac5e16d2, []int{5}
}
func (m *GetUpdateDateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUpdateDateRequest.Unmarshal(m, b)
}
func (m *GetUpdateDateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUpdateDateRequest.Marshal(b, m, deterministic)
}
func (dst *GetUpdateDateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUpdateDateRequest.Merge(dst, src)
}
func (m *GetUpdateDateRequest) XXX_Size() int {
	return xxx_messageInfo_GetUpdateDateRequest.Size(m)
}
func (m *GetUpdateDateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUpdateDateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUpdateDateRequest proto.InternalMessageInfo

func (m *GetUpdateDateRequest) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type GetUpdateDateResponse struct {
	Dates                map[string]string `protobuf:"bytes,1,rep,name=dates,proto3" json:"dates,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Err                  string            `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetUpdateDateResponse) Reset()         { *m = GetUpdateDateResponse{} }
func (m *GetUpdateDateResponse) String() string { return proto.CompactTextString(m) }
func (*GetUpdateDateResponse) ProtoMessage()    {}
func (*GetUpdateDateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_hourlysvc_a575eba4ac5e16d2, []int{6}
}
func (m *GetUpdateDateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUpdateDateResponse.Unmarshal(m, b)
}
func (m *GetUpdateDateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUpdateDateResponse.Marshal(b, m, deterministic)
}
func (dst *GetUpdateDateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUpdateDateResponse.Merge(dst, src)
}
func (m *GetUpdateDateResponse) XXX_Size() int {
	return xxx_messageInfo_GetUpdateDateResponse.Size(m)
}
func (m *GetUpdateDateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUpdateDateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUpdateDateResponse proto.InternalMessageInfo

func (m *GetUpdateDateResponse) GetDates() map[string]string {
	if m != nil {
		return m.Dates
	}
	return nil
}

func (m *GetUpdateDateResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*Temperature)(nil), "grpc.Temperature")
	proto.RegisterType((*GetPeriodRequest)(nil), "grpc.GetPeriodRequest")
	proto.RegisterType((*GetPeriodResponse)(nil), "grpc.GetPeriodResponse")
	proto.RegisterType((*PushPeriodRequest)(nil), "grpc.PushPeriodRequest")
	proto.RegisterType((*PushPeriodResponse)(nil), "grpc.PushPeriodResponse")
	proto.RegisterType((*GetUpdateDateRequest)(nil), "grpc.GetUpdateDateRequest")
	proto.RegisterType((*GetUpdateDateResponse)(nil), "grpc.GetUpdateDateResponse")
	proto.RegisterMapType((map[string]string)(nil), "grpc.GetUpdateDateResponse.DatesEntry")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HourlySVCClient is the client API for HourlySVC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HourlySVCClient interface {
	GetPeriod(ctx context.Context, in *GetPeriodRequest, opts ...grpc.CallOption) (*GetPeriodResponse, error)
	PushPeriod(ctx context.Context, in *PushPeriodRequest, opts ...grpc.CallOption) (*PushPeriodResponse, error)
	GetUpdateDate(ctx context.Context, in *GetUpdateDateRequest, opts ...grpc.CallOption) (*GetUpdateDateResponse, error)
}

type hourlySVCClient struct {
	cc *grpc.ClientConn
}

func NewHourlySVCClient(cc *grpc.ClientConn) HourlySVCClient {
	return &hourlySVCClient{cc}
}

func (c *hourlySVCClient) GetPeriod(ctx context.Context, in *GetPeriodRequest, opts ...grpc.CallOption) (*GetPeriodResponse, error) {
	out := new(GetPeriodResponse)
	err := c.cc.Invoke(ctx, "/grpc.HourlySVC/GetPeriod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hourlySVCClient) PushPeriod(ctx context.Context, in *PushPeriodRequest, opts ...grpc.CallOption) (*PushPeriodResponse, error) {
	out := new(PushPeriodResponse)
	err := c.cc.Invoke(ctx, "/grpc.HourlySVC/PushPeriod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hourlySVCClient) GetUpdateDate(ctx context.Context, in *GetUpdateDateRequest, opts ...grpc.CallOption) (*GetUpdateDateResponse, error) {
	out := new(GetUpdateDateResponse)
	err := c.cc.Invoke(ctx, "/grpc.HourlySVC/GetUpdateDate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HourlySVCServer is the server API for HourlySVC service.
type HourlySVCServer interface {
	GetPeriod(context.Context, *GetPeriodRequest) (*GetPeriodResponse, error)
	PushPeriod(context.Context, *PushPeriodRequest) (*PushPeriodResponse, error)
	GetUpdateDate(context.Context, *GetUpdateDateRequest) (*GetUpdateDateResponse, error)
}

func RegisterHourlySVCServer(s *grpc.Server, srv HourlySVCServer) {
	s.RegisterService(&_HourlySVC_serviceDesc, srv)
}

func _HourlySVC_GetPeriod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPeriodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HourlySVCServer).GetPeriod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.HourlySVC/GetPeriod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HourlySVCServer).GetPeriod(ctx, req.(*GetPeriodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HourlySVC_PushPeriod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushPeriodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HourlySVCServer).PushPeriod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.HourlySVC/PushPeriod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HourlySVCServer).PushPeriod(ctx, req.(*PushPeriodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HourlySVC_GetUpdateDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUpdateDateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HourlySVCServer).GetUpdateDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.HourlySVC/GetUpdateDate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HourlySVCServer).GetUpdateDate(ctx, req.(*GetUpdateDateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HourlySVC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.HourlySVC",
	HandlerType: (*HourlySVCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPeriod",
			Handler:    _HourlySVC_GetPeriod_Handler,
		},
		{
			MethodName: "PushPeriod",
			Handler:    _HourlySVC_PushPeriod_Handler,
		},
		{
			MethodName: "GetUpdateDate",
			Handler:    _HourlySVC_GetUpdateDate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hourlysvc.proto",
}

func init() { proto.RegisterFile("hourlysvc.proto", fileDescriptor_hourlysvc_a575eba4ac5e16d2) }

var fileDescriptor_hourlysvc_a575eba4ac5e16d2 = []byte{
	// 414 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0xcb, 0x8e, 0xd3, 0x30,
	0x14, 0xad, 0x93, 0x16, 0x29, 0xb7, 0x02, 0xa6, 0xd6, 0x30, 0x44, 0x61, 0x41, 0xe4, 0xc5, 0xd0,
	0x0d, 0x19, 0xa9, 0x6c, 0x2a, 0x84, 0x90, 0xa0, 0xa0, 0xa2, 0x0a, 0xa1, 0x2a, 0x3c, 0xf6, 0x69,
	0x63, 0xd2, 0xa8, 0x0f, 0x07, 0xdb, 0xa9, 0x94, 0xcf, 0xe1, 0x6f, 0xf8, 0x06, 0x16, 0x7c, 0x0b,
	0xb2, 0x9d, 0x57, 0x27, 0x55, 0x77, 0xf7, 0x79, 0xce, 0xf1, 0xb9, 0x09, 0x3c, 0xde, 0xb0, 0x9c,
	0xef, 0x0a, 0x71, 0x5c, 0x07, 0x19, 0x67, 0x92, 0xe1, 0x7e, 0xc2, 0xb3, 0xb5, 0xf7, 0x32, 0x49,
	0xe5, 0x26, 0x5f, 0x05, 0x6b, 0xb6, 0xbf, 0x4b, 0x58, 0xc2, 0xee, 0x74, 0x73, 0x95, 0xff, 0xd4,
	0x99, 0x4e, 0x74, 0x64, 0x96, 0xc8, 0x0c, 0x86, 0xdf, 0xe8, 0x3e, 0xa3, 0x3c, 0x92, 0x39, 0xa7,
	0x18, 0x43, 0x3f, 0x8e, 0x24, 0x75, 0x91, 0x8f, 0xc6, 0x4e, 0xa8, 0x63, 0xec, 0xc3, 0x50, 0x36,
	0x23, 0xae, 0xe5, 0xa3, 0xb1, 0x15, 0xb6, 0x4b, 0x64, 0x01, 0x57, 0x73, 0x2a, 0x97, 0x94, 0xa7,
	0x2c, 0x0e, 0xe9, 0xaf, 0x9c, 0x0a, 0x89, 0x1f, 0x81, 0x95, 0xc6, 0x25, 0x8e, 0x95, 0xc6, 0xf8,
	0x1a, 0x06, 0x42, 0x46, 0x5c, 0xea, 0x7d, 0x27, 0x34, 0x09, 0xbe, 0x02, 0x9b, 0x1e, 0x62, 0xd7,
	0xd6, 0x35, 0x15, 0x92, 0x2f, 0x30, 0x6a, 0x61, 0x89, 0x8c, 0x1d, 0x04, 0xc5, 0x2f, 0x60, 0xa0,
	0xf8, 0x84, 0x8b, 0x7c, 0x7b, 0x3c, 0x9c, 0x8c, 0x02, 0xf5, 0xd4, 0xa0, 0x25, 0x3c, 0x34, 0x7d,
	0x8d, 0xc7, 0x79, 0xc9, 0xa1, 0x42, 0xf2, 0x19, 0x46, 0xcb, 0x5c, 0x6c, 0x2e, 0x8b, 0xab, 0xf1,
	0xad, 0xcb, 0xf8, 0xe4, 0x16, 0x70, 0x1b, 0xad, 0x94, 0x57, 0xb2, 0xa2, 0x86, 0x35, 0x80, 0xeb,
	0x39, 0x95, 0xdf, 0x33, 0x65, 0xe0, 0x87, 0x48, 0xd2, 0x8a, 0xf8, 0x06, 0xec, 0x34, 0x36, 0xcf,
	0x70, 0xde, 0xf7, 0xff, 0xfc, 0x7b, 0xde, 0x0b, 0x55, 0x81, 0xfc, 0x46, 0xf0, 0xe4, 0xde, 0x42,
	0x89, 0xfd, 0x06, 0x06, 0xaa, 0x56, 0x3d, 0xfd, 0xd6, 0x48, 0x3b, 0x3b, 0x1b, 0xa8, 0x44, 0x7c,
	0x3c, 0x48, 0x5e, 0x84, 0x66, 0xa9, 0xeb, 0x87, 0x37, 0x05, 0x68, 0xc6, 0x54, 0x7f, 0x4b, 0x8b,
	0x4a, 0xf9, 0x96, 0x16, 0xea, 0x4e, 0xc7, 0x68, 0x97, 0xd3, 0xea, 0x4e, 0x3a, 0x79, 0x6d, 0x4d,
	0xd1, 0xe4, 0x2f, 0x02, 0xe7, 0x93, 0xfe, 0xe6, 0xbe, 0xfe, 0x98, 0xe1, 0xb7, 0xe0, 0xd4, 0x77,
	0xc2, 0x37, 0xb5, 0xaa, 0x13, 0x9f, 0xbd, 0xa7, 0x9d, 0xba, 0x51, 0x4a, 0x7a, 0xf8, 0x1d, 0x40,
	0xe3, 0x24, 0x2e, 0x07, 0x3b, 0x97, 0xf2, 0xdc, 0x6e, 0xa3, 0x86, 0x58, 0xc0, 0xc3, 0x13, 0x1f,
	0xb0, 0x77, 0xd6, 0x1c, 0x03, 0xf4, 0xec, 0x82, 0x71, 0xa4, 0xb7, 0x7a, 0xa0, 0x7f, 0x87, 0x57,
	0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x45, 0x24, 0xd3, 0xe1, 0x56, 0x03, 0x00, 0x00,
}
