// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alertssvc.proto

package altgrpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Alert struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Desc                 string            `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Params               map[string]string `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Alert) Reset()         { *m = Alert{} }
func (m *Alert) String() string { return proto.CompactTextString(m) }
func (*Alert) ProtoMessage()    {}
func (*Alert) Descriptor() ([]byte, []int) {
	return fileDescriptor_alertssvc_d3d9dad2e2fad7f6, []int{0}
}
func (m *Alert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Alert.Unmarshal(m, b)
}
func (m *Alert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Alert.Marshal(b, m, deterministic)
}
func (dst *Alert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Alert.Merge(dst, src)
}
func (m *Alert) XXX_Size() int {
	return xxx_messageInfo_Alert.Size(m)
}
func (m *Alert) XXX_DiscardUnknown() {
	xxx_messageInfo_Alert.DiscardUnknown(m)
}

var xxx_messageInfo_Alert proto.InternalMessageInfo

func (m *Alert) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Alert) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Alert) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

type SendAlertRequest struct {
	Alert                *Alert   `protobuf:"bytes,1,opt,name=alert,proto3" json:"alert,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendAlertRequest) Reset()         { *m = SendAlertRequest{} }
func (m *SendAlertRequest) String() string { return proto.CompactTextString(m) }
func (*SendAlertRequest) ProtoMessage()    {}
func (*SendAlertRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_alertssvc_d3d9dad2e2fad7f6, []int{1}
}
func (m *SendAlertRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendAlertRequest.Unmarshal(m, b)
}
func (m *SendAlertRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendAlertRequest.Marshal(b, m, deterministic)
}
func (dst *SendAlertRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendAlertRequest.Merge(dst, src)
}
func (m *SendAlertRequest) XXX_Size() int {
	return xxx_messageInfo_SendAlertRequest.Size(m)
}
func (m *SendAlertRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendAlertRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendAlertRequest proto.InternalMessageInfo

func (m *SendAlertRequest) GetAlert() *Alert {
	if m != nil {
		return m.Alert
	}
	return nil
}

type SendAlertResponse struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendAlertResponse) Reset()         { *m = SendAlertResponse{} }
func (m *SendAlertResponse) String() string { return proto.CompactTextString(m) }
func (*SendAlertResponse) ProtoMessage()    {}
func (*SendAlertResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_alertssvc_d3d9dad2e2fad7f6, []int{2}
}
func (m *SendAlertResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendAlertResponse.Unmarshal(m, b)
}
func (m *SendAlertResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendAlertResponse.Marshal(b, m, deterministic)
}
func (dst *SendAlertResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendAlertResponse.Merge(dst, src)
}
func (m *SendAlertResponse) XXX_Size() int {
	return xxx_messageInfo_SendAlertResponse.Size(m)
}
func (m *SendAlertResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendAlertResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendAlertResponse proto.InternalMessageInfo

func (m *SendAlertResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*Alert)(nil), "altgrpc.Alert")
	proto.RegisterMapType((map[string]string)(nil), "altgrpc.Alert.ParamsEntry")
	proto.RegisterType((*SendAlertRequest)(nil), "altgrpc.SendAlertRequest")
	proto.RegisterType((*SendAlertResponse)(nil), "altgrpc.SendAlertResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AlertSVCClient is the client API for AlertSVC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AlertSVCClient interface {
	SendAlert(ctx context.Context, in *SendAlertRequest, opts ...grpc.CallOption) (*SendAlertResponse, error)
}

type alertSVCClient struct {
	cc *grpc.ClientConn
}

func NewAlertSVCClient(cc *grpc.ClientConn) AlertSVCClient {
	return &alertSVCClient{cc}
}

func (c *alertSVCClient) SendAlert(ctx context.Context, in *SendAlertRequest, opts ...grpc.CallOption) (*SendAlertResponse, error) {
	out := new(SendAlertResponse)
	err := c.cc.Invoke(ctx, "/altgrpc.AlertSVC/SendAlert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlertSVCServer is the server API for AlertSVC service.
type AlertSVCServer interface {
	SendAlert(context.Context, *SendAlertRequest) (*SendAlertResponse, error)
}

func RegisterAlertSVCServer(s *grpc.Server, srv AlertSVCServer) {
	s.RegisterService(&_AlertSVC_serviceDesc, srv)
}

func _AlertSVC_SendAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertSVCServer).SendAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/altgrpc.AlertSVC/SendAlert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertSVCServer).SendAlert(ctx, req.(*SendAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AlertSVC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "altgrpc.AlertSVC",
	HandlerType: (*AlertSVCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendAlert",
			Handler:    _AlertSVC_SendAlert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "alertssvc.proto",
}

func init() { proto.RegisterFile("alertssvc.proto", fileDescriptor_alertssvc_d3d9dad2e2fad7f6) }

var fileDescriptor_alertssvc_d3d9dad2e2fad7f6 = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x49, 0x43, 0x0a, 0xbd, 0x48, 0x50, 0x4e, 0x0c, 0x21, 0x53, 0x15, 0x81, 0xd4, 0x29,
	0x43, 0x58, 0x0a, 0x1b, 0x02, 0xf6, 0x2a, 0x95, 0xd8, 0x4d, 0x7a, 0x62, 0x20, 0x4d, 0xcc, 0xd9,
	0xad, 0xd4, 0x3f, 0xc3, 0x6f, 0x45, 0x3e, 0x9b, 0x2a, 0xa0, 0x6e, 0x2f, 0xef, 0xdd, 0xbd, 0xef,
	0x62, 0xb8, 0x54, 0x2d, 0xb1, 0x35, 0x66, 0xd7, 0x94, 0x9a, 0x7b, 0xdb, 0xe3, 0x99, 0x6a, 0xed,
	0x07, 0xeb, 0xa6, 0xf8, 0x8e, 0x20, 0x79, 0x72, 0x21, 0x22, 0x9c, 0x76, 0x6a, 0x43, 0x59, 0x34,
	0x8b, 0xe6, 0x93, 0x5a, 0xb4, 0xf3, 0xd6, 0x64, 0x9a, 0x6c, 0xe4, 0x3d, 0xa7, 0xb1, 0x82, 0xb1,
	0x56, 0xac, 0x36, 0x26, 0x8b, 0x67, 0xf1, 0x3c, 0xad, 0xf2, 0x32, 0x74, 0x95, 0xd2, 0x53, 0x2e,
	0x25, 0x7c, 0xed, 0x2c, 0xef, 0xeb, 0x30, 0x99, 0x3f, 0x40, 0x3a, 0xb0, 0x71, 0x0a, 0xf1, 0x27,
	0xed, 0x03, 0xc9, 0x49, 0xbc, 0x86, 0x64, 0xa7, 0xda, 0x2d, 0x05, 0x92, 0xff, 0x78, 0x1c, 0x2d,
	0xa2, 0x62, 0x01, 0xd3, 0x15, 0x75, 0x6b, 0xe9, 0xae, 0xe9, 0x6b, 0x4b, 0xc6, 0xe2, 0x2d, 0x24,
	0xf2, 0x43, 0xd2, 0x90, 0x56, 0x17, 0x7f, 0x2f, 0xa8, 0x7d, 0x58, 0xdc, 0xc1, 0xd5, 0x60, 0xd3,
	0xe8, 0xbe, 0x33, 0xe4, 0xd0, 0xc4, 0xfc, 0x8b, 0x26, 0xe6, 0x6a, 0x09, 0xe7, 0x32, 0xb2, 0x7a,
	0x7b, 0xc6, 0x17, 0x98, 0x1c, 0x56, 0xf0, 0xe6, 0x50, 0xfb, 0xff, 0x80, 0x3c, 0x3f, 0x16, 0x79,
	0x42, 0x71, 0xf2, 0x3e, 0x96, 0x37, 0xbe, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x6c, 0x4c, 0xea,
	0x6c, 0x76, 0x01, 0x00, 0x00,
}
