// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.17.3
// source: autocompletesvc.proto

package acrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AutocompleteSVC_GetAutocomplete_FullMethodName = "/acrpc.AutocompleteSVC/GetAutocomplete"
	AutocompleteSVC_AddSources_FullMethodName      = "/acrpc.AutocompleteSVC/AddSources"
	AutocompleteSVC_ResetSources_FullMethodName    = "/acrpc.AutocompleteSVC/ResetSources"
	AutocompleteSVC_GetAllStations_FullMethodName  = "/acrpc.AutocompleteSVC/GetAllStations"
)

// AutocompleteSVCClient is the client API for AutocompleteSVC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AutocompleteSVCClient interface {
	GetAutocomplete(ctx context.Context, in *GetAutocompleteRequest, opts ...grpc.CallOption) (*GetAutocompleteResponse, error)
	AddSources(ctx context.Context, in *AddSourcesRequest, opts ...grpc.CallOption) (*AddSourcesResponse, error)
	ResetSources(ctx context.Context, in *ResetSourcesRequest, opts ...grpc.CallOption) (*ResetSourcesResponse, error)
	GetAllStations(ctx context.Context, in *GetAllStationsRequest, opts ...grpc.CallOption) (*GetAllStationsResponse, error)
}

type autocompleteSVCClient struct {
	cc grpc.ClientConnInterface
}

func NewAutocompleteSVCClient(cc grpc.ClientConnInterface) AutocompleteSVCClient {
	return &autocompleteSVCClient{cc}
}

func (c *autocompleteSVCClient) GetAutocomplete(ctx context.Context, in *GetAutocompleteRequest, opts ...grpc.CallOption) (*GetAutocompleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAutocompleteResponse)
	err := c.cc.Invoke(ctx, AutocompleteSVC_GetAutocomplete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autocompleteSVCClient) AddSources(ctx context.Context, in *AddSourcesRequest, opts ...grpc.CallOption) (*AddSourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddSourcesResponse)
	err := c.cc.Invoke(ctx, AutocompleteSVC_AddSources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autocompleteSVCClient) ResetSources(ctx context.Context, in *ResetSourcesRequest, opts ...grpc.CallOption) (*ResetSourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetSourcesResponse)
	err := c.cc.Invoke(ctx, AutocompleteSVC_ResetSources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autocompleteSVCClient) GetAllStations(ctx context.Context, in *GetAllStationsRequest, opts ...grpc.CallOption) (*GetAllStationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllStationsResponse)
	err := c.cc.Invoke(ctx, AutocompleteSVC_GetAllStations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AutocompleteSVCServer is the server API for AutocompleteSVC service.
// All implementations should embed UnimplementedAutocompleteSVCServer
// for forward compatibility.
type AutocompleteSVCServer interface {
	GetAutocomplete(context.Context, *GetAutocompleteRequest) (*GetAutocompleteResponse, error)
	AddSources(context.Context, *AddSourcesRequest) (*AddSourcesResponse, error)
	ResetSources(context.Context, *ResetSourcesRequest) (*ResetSourcesResponse, error)
	GetAllStations(context.Context, *GetAllStationsRequest) (*GetAllStationsResponse, error)
}

// UnimplementedAutocompleteSVCServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAutocompleteSVCServer struct{}

func (UnimplementedAutocompleteSVCServer) GetAutocomplete(context.Context, *GetAutocompleteRequest) (*GetAutocompleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAutocomplete not implemented")
}
func (UnimplementedAutocompleteSVCServer) AddSources(context.Context, *AddSourcesRequest) (*AddSourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSources not implemented")
}
func (UnimplementedAutocompleteSVCServer) ResetSources(context.Context, *ResetSourcesRequest) (*ResetSourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetSources not implemented")
}
func (UnimplementedAutocompleteSVCServer) GetAllStations(context.Context, *GetAllStationsRequest) (*GetAllStationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllStations not implemented")
}
func (UnimplementedAutocompleteSVCServer) testEmbeddedByValue() {}

// UnsafeAutocompleteSVCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AutocompleteSVCServer will
// result in compilation errors.
type UnsafeAutocompleteSVCServer interface {
	mustEmbedUnimplementedAutocompleteSVCServer()
}

func RegisterAutocompleteSVCServer(s grpc.ServiceRegistrar, srv AutocompleteSVCServer) {
	// If the following call pancis, it indicates UnimplementedAutocompleteSVCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AutocompleteSVC_ServiceDesc, srv)
}

func _AutocompleteSVC_GetAutocomplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAutocompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutocompleteSVCServer).GetAutocomplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutocompleteSVC_GetAutocomplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutocompleteSVCServer).GetAutocomplete(ctx, req.(*GetAutocompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutocompleteSVC_AddSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutocompleteSVCServer).AddSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutocompleteSVC_AddSources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutocompleteSVCServer).AddSources(ctx, req.(*AddSourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutocompleteSVC_ResetSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetSourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutocompleteSVCServer).ResetSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutocompleteSVC_ResetSources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutocompleteSVCServer).ResetSources(ctx, req.(*ResetSourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutocompleteSVC_GetAllStations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllStationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutocompleteSVCServer).GetAllStations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutocompleteSVC_GetAllStations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutocompleteSVCServer).GetAllStations(ctx, req.(*GetAllStationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AutocompleteSVC_ServiceDesc is the grpc.ServiceDesc for AutocompleteSVC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AutocompleteSVC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "acrpc.AutocompleteSVC",
	HandlerType: (*AutocompleteSVCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAutocomplete",
			Handler:    _AutocompleteSVC_GetAutocomplete_Handler,
		},
		{
			MethodName: "AddSources",
			Handler:    _AutocompleteSVC_AddSources_Handler,
		},
		{
			MethodName: "ResetSources",
			Handler:    _AutocompleteSVC_ResetSources_Handler,
		},
		{
			MethodName: "GetAllStations",
			Handler:    _AutocompleteSVC_GetAllStations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "autocompletesvc.proto",
}
