// Code generated by protoc-gen-go. DO NOT EDIT.
// source: autocompletesvc.proto

package acrpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Source struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Icao                 string   `protobuf:"bytes,3,opt,name=Icao,proto3" json:"Icao,omitempty"`
	Dwd                  string   `protobuf:"bytes,4,opt,name=Dwd,proto3" json:"Dwd,omitempty"`
	Wmo                  string   `protobuf:"bytes,5,opt,name=Wmo,proto3" json:"Wmo,omitempty"`
	Cwop                 string   `protobuf:"bytes,6,opt,name=Cwop,proto3" json:"Cwop,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Source) Reset()         { *m = Source{} }
func (m *Source) String() string { return proto.CompactTextString(m) }
func (*Source) ProtoMessage()    {}
func (*Source) Descriptor() ([]byte, []int) {
	return fileDescriptor_autocompletesvc_7c4561b83d790229, []int{0}
}
func (m *Source) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Source.Unmarshal(m, b)
}
func (m *Source) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Source.Marshal(b, m, deterministic)
}
func (dst *Source) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Source.Merge(dst, src)
}
func (m *Source) XXX_Size() int {
	return xxx_messageInfo_Source.Size(m)
}
func (m *Source) XXX_DiscardUnknown() {
	xxx_messageInfo_Source.DiscardUnknown(m)
}

var xxx_messageInfo_Source proto.InternalMessageInfo

func (m *Source) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Source) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Source) GetIcao() string {
	if m != nil {
		return m.Icao
	}
	return ""
}

func (m *Source) GetDwd() string {
	if m != nil {
		return m.Dwd
	}
	return ""
}

func (m *Source) GetWmo() string {
	if m != nil {
		return m.Wmo
	}
	return ""
}

func (m *Source) GetCwop() string {
	if m != nil {
		return m.Cwop
	}
	return ""
}

type Sources struct {
	Sources              []*Source `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Sources) Reset()         { *m = Sources{} }
func (m *Sources) String() string { return proto.CompactTextString(m) }
func (*Sources) ProtoMessage()    {}
func (*Sources) Descriptor() ([]byte, []int) {
	return fileDescriptor_autocompletesvc_7c4561b83d790229, []int{1}
}
func (m *Sources) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sources.Unmarshal(m, b)
}
func (m *Sources) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sources.Marshal(b, m, deterministic)
}
func (dst *Sources) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sources.Merge(dst, src)
}
func (m *Sources) XXX_Size() int {
	return xxx_messageInfo_Sources.Size(m)
}
func (m *Sources) XXX_DiscardUnknown() {
	xxx_messageInfo_Sources.DiscardUnknown(m)
}

var xxx_messageInfo_Sources proto.InternalMessageInfo

func (m *Sources) GetSources() []*Source {
	if m != nil {
		return m.Sources
	}
	return nil
}

type GetAutocompleteRequest struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAutocompleteRequest) Reset()         { *m = GetAutocompleteRequest{} }
func (m *GetAutocompleteRequest) String() string { return proto.CompactTextString(m) }
func (*GetAutocompleteRequest) ProtoMessage()    {}
func (*GetAutocompleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_autocompletesvc_7c4561b83d790229, []int{2}
}
func (m *GetAutocompleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAutocompleteRequest.Unmarshal(m, b)
}
func (m *GetAutocompleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAutocompleteRequest.Marshal(b, m, deterministic)
}
func (dst *GetAutocompleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAutocompleteRequest.Merge(dst, src)
}
func (m *GetAutocompleteRequest) XXX_Size() int {
	return xxx_messageInfo_GetAutocompleteRequest.Size(m)
}
func (m *GetAutocompleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAutocompleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAutocompleteRequest proto.InternalMessageInfo

func (m *GetAutocompleteRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type GetAutocompleteResponse struct {
	Result               map[string]*Sources `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Err                  string              `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetAutocompleteResponse) Reset()         { *m = GetAutocompleteResponse{} }
func (m *GetAutocompleteResponse) String() string { return proto.CompactTextString(m) }
func (*GetAutocompleteResponse) ProtoMessage()    {}
func (*GetAutocompleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_autocompletesvc_7c4561b83d790229, []int{3}
}
func (m *GetAutocompleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAutocompleteResponse.Unmarshal(m, b)
}
func (m *GetAutocompleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAutocompleteResponse.Marshal(b, m, deterministic)
}
func (dst *GetAutocompleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAutocompleteResponse.Merge(dst, src)
}
func (m *GetAutocompleteResponse) XXX_Size() int {
	return xxx_messageInfo_GetAutocompleteResponse.Size(m)
}
func (m *GetAutocompleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAutocompleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAutocompleteResponse proto.InternalMessageInfo

func (m *GetAutocompleteResponse) GetResult() map[string]*Sources {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GetAutocompleteResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type AddSourcesRequest struct {
	Sources              []*Source `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddSourcesRequest) Reset()         { *m = AddSourcesRequest{} }
func (m *AddSourcesRequest) String() string { return proto.CompactTextString(m) }
func (*AddSourcesRequest) ProtoMessage()    {}
func (*AddSourcesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_autocompletesvc_7c4561b83d790229, []int{4}
}
func (m *AddSourcesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddSourcesRequest.Unmarshal(m, b)
}
func (m *AddSourcesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddSourcesRequest.Marshal(b, m, deterministic)
}
func (dst *AddSourcesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddSourcesRequest.Merge(dst, src)
}
func (m *AddSourcesRequest) XXX_Size() int {
	return xxx_messageInfo_AddSourcesRequest.Size(m)
}
func (m *AddSourcesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddSourcesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddSourcesRequest proto.InternalMessageInfo

func (m *AddSourcesRequest) GetSources() []*Source {
	if m != nil {
		return m.Sources
	}
	return nil
}

type AddSourcesResponse struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddSourcesResponse) Reset()         { *m = AddSourcesResponse{} }
func (m *AddSourcesResponse) String() string { return proto.CompactTextString(m) }
func (*AddSourcesResponse) ProtoMessage()    {}
func (*AddSourcesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_autocompletesvc_7c4561b83d790229, []int{5}
}
func (m *AddSourcesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddSourcesResponse.Unmarshal(m, b)
}
func (m *AddSourcesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddSourcesResponse.Marshal(b, m, deterministic)
}
func (dst *AddSourcesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddSourcesResponse.Merge(dst, src)
}
func (m *AddSourcesResponse) XXX_Size() int {
	return xxx_messageInfo_AddSourcesResponse.Size(m)
}
func (m *AddSourcesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddSourcesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddSourcesResponse proto.InternalMessageInfo

func (m *AddSourcesResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type ResetSourcesRequest struct {
	Sources              []*Source `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ResetSourcesRequest) Reset()         { *m = ResetSourcesRequest{} }
func (m *ResetSourcesRequest) String() string { return proto.CompactTextString(m) }
func (*ResetSourcesRequest) ProtoMessage()    {}
func (*ResetSourcesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_autocompletesvc_7c4561b83d790229, []int{6}
}
func (m *ResetSourcesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetSourcesRequest.Unmarshal(m, b)
}
func (m *ResetSourcesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetSourcesRequest.Marshal(b, m, deterministic)
}
func (dst *ResetSourcesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetSourcesRequest.Merge(dst, src)
}
func (m *ResetSourcesRequest) XXX_Size() int {
	return xxx_messageInfo_ResetSourcesRequest.Size(m)
}
func (m *ResetSourcesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetSourcesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetSourcesRequest proto.InternalMessageInfo

func (m *ResetSourcesRequest) GetSources() []*Source {
	if m != nil {
		return m.Sources
	}
	return nil
}

type ResetSourcesResponse struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetSourcesResponse) Reset()         { *m = ResetSourcesResponse{} }
func (m *ResetSourcesResponse) String() string { return proto.CompactTextString(m) }
func (*ResetSourcesResponse) ProtoMessage()    {}
func (*ResetSourcesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_autocompletesvc_7c4561b83d790229, []int{7}
}
func (m *ResetSourcesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetSourcesResponse.Unmarshal(m, b)
}
func (m *ResetSourcesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetSourcesResponse.Marshal(b, m, deterministic)
}
func (dst *ResetSourcesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetSourcesResponse.Merge(dst, src)
}
func (m *ResetSourcesResponse) XXX_Size() int {
	return xxx_messageInfo_ResetSourcesResponse.Size(m)
}
func (m *ResetSourcesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetSourcesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetSourcesResponse proto.InternalMessageInfo

func (m *ResetSourcesResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*Source)(nil), "acrpc.Source")
	proto.RegisterType((*Sources)(nil), "acrpc.Sources")
	proto.RegisterType((*GetAutocompleteRequest)(nil), "acrpc.GetAutocompleteRequest")
	proto.RegisterType((*GetAutocompleteResponse)(nil), "acrpc.GetAutocompleteResponse")
	proto.RegisterMapType((map[string]*Sources)(nil), "acrpc.GetAutocompleteResponse.ResultEntry")
	proto.RegisterType((*AddSourcesRequest)(nil), "acrpc.AddSourcesRequest")
	proto.RegisterType((*AddSourcesResponse)(nil), "acrpc.AddSourcesResponse")
	proto.RegisterType((*ResetSourcesRequest)(nil), "acrpc.ResetSourcesRequest")
	proto.RegisterType((*ResetSourcesResponse)(nil), "acrpc.ResetSourcesResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AutocompleteSVCClient is the client API for AutocompleteSVC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AutocompleteSVCClient interface {
	GetAutocomplete(ctx context.Context, in *GetAutocompleteRequest, opts ...grpc.CallOption) (*GetAutocompleteResponse, error)
	AddSources(ctx context.Context, in *AddSourcesRequest, opts ...grpc.CallOption) (*AddSourcesResponse, error)
	ResetSources(ctx context.Context, in *ResetSourcesRequest, opts ...grpc.CallOption) (*ResetSourcesResponse, error)
}

type autocompleteSVCClient struct {
	cc *grpc.ClientConn
}

func NewAutocompleteSVCClient(cc *grpc.ClientConn) AutocompleteSVCClient {
	return &autocompleteSVCClient{cc}
}

func (c *autocompleteSVCClient) GetAutocomplete(ctx context.Context, in *GetAutocompleteRequest, opts ...grpc.CallOption) (*GetAutocompleteResponse, error) {
	out := new(GetAutocompleteResponse)
	err := c.cc.Invoke(ctx, "/acrpc.AutocompleteSVC/GetAutocomplete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autocompleteSVCClient) AddSources(ctx context.Context, in *AddSourcesRequest, opts ...grpc.CallOption) (*AddSourcesResponse, error) {
	out := new(AddSourcesResponse)
	err := c.cc.Invoke(ctx, "/acrpc.AutocompleteSVC/AddSources", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autocompleteSVCClient) ResetSources(ctx context.Context, in *ResetSourcesRequest, opts ...grpc.CallOption) (*ResetSourcesResponse, error) {
	out := new(ResetSourcesResponse)
	err := c.cc.Invoke(ctx, "/acrpc.AutocompleteSVC/ResetSources", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AutocompleteSVCServer is the server API for AutocompleteSVC service.
type AutocompleteSVCServer interface {
	GetAutocomplete(context.Context, *GetAutocompleteRequest) (*GetAutocompleteResponse, error)
	AddSources(context.Context, *AddSourcesRequest) (*AddSourcesResponse, error)
	ResetSources(context.Context, *ResetSourcesRequest) (*ResetSourcesResponse, error)
}

func RegisterAutocompleteSVCServer(s *grpc.Server, srv AutocompleteSVCServer) {
	s.RegisterService(&_AutocompleteSVC_serviceDesc, srv)
}

func _AutocompleteSVC_GetAutocomplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAutocompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutocompleteSVCServer).GetAutocomplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acrpc.AutocompleteSVC/GetAutocomplete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutocompleteSVCServer).GetAutocomplete(ctx, req.(*GetAutocompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutocompleteSVC_AddSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutocompleteSVCServer).AddSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acrpc.AutocompleteSVC/AddSources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutocompleteSVCServer).AddSources(ctx, req.(*AddSourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutocompleteSVC_ResetSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetSourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutocompleteSVCServer).ResetSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acrpc.AutocompleteSVC/ResetSources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutocompleteSVCServer).ResetSources(ctx, req.(*ResetSourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AutocompleteSVC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "acrpc.AutocompleteSVC",
	HandlerType: (*AutocompleteSVCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAutocomplete",
			Handler:    _AutocompleteSVC_GetAutocomplete_Handler,
		},
		{
			MethodName: "AddSources",
			Handler:    _AutocompleteSVC_AddSources_Handler,
		},
		{
			MethodName: "ResetSources",
			Handler:    _AutocompleteSVC_ResetSources_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "autocompletesvc.proto",
}

func init() {
	proto.RegisterFile("autocompletesvc.proto", fileDescriptor_autocompletesvc_7c4561b83d790229)
}

var fileDescriptor_autocompletesvc_7c4561b83d790229 = []byte{
	// 389 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4b, 0x4f, 0xea, 0x40,
	0x14, 0xbe, 0x2d, 0x50, 0x72, 0x0f, 0xf7, 0xc2, 0xbd, 0xe3, 0x6b, 0xac, 0xd1, 0x90, 0xc6, 0x28,
	0x31, 0xa6, 0x8b, 0xba, 0x31, 0xc6, 0x98, 0x20, 0x18, 0xd3, 0x8d, 0x8b, 0x21, 0x91, 0x75, 0x2d,
	0xb3, 0x92, 0x32, 0xb5, 0x33, 0xe5, 0xf1, 0xd7, 0xfc, 0x5f, 0xee, 0xcd, 0x3c, 0xc0, 0x22, 0x60,
	0x8c, 0xbb, 0x2f, 0xe7, 0x7c, 0xa7, 0xdf, 0x63, 0x52, 0xd8, 0x89, 0x72, 0xc1, 0x62, 0x96, 0xa4,
	0x43, 0x2a, 0x28, 0x1f, 0xc7, 0x7e, 0x9a, 0x31, 0xc1, 0x50, 0x25, 0x8a, 0xb3, 0x34, 0xf6, 0xa6,
	0xe0, 0xf4, 0x58, 0x9e, 0xc5, 0x14, 0xd5, 0xc1, 0x0e, 0xbb, 0xd8, 0x6a, 0x5a, 0xad, 0xdf, 0xc4,
	0x0e, 0xbb, 0x08, 0x41, 0xf9, 0x21, 0x4a, 0x28, 0xb6, 0xd5, 0x44, 0x61, 0x39, 0x0b, 0xe3, 0x88,
	0xe1, 0x92, 0x9e, 0x49, 0x8c, 0xfe, 0x41, 0xa9, 0x3b, 0x19, 0xe0, 0xb2, 0x1a, 0x49, 0x28, 0x27,
	0xfd, 0x84, 0xe1, 0x8a, 0x9e, 0xf4, 0x13, 0x26, 0xef, 0x3a, 0x13, 0x96, 0x62, 0x47, 0xdf, 0x49,
	0xec, 0x05, 0x50, 0xd5, 0xca, 0x1c, 0x9d, 0x42, 0x95, 0x6b, 0x88, 0xad, 0x66, 0xa9, 0x55, 0x0b,
	0xfe, 0xfa, 0xca, 0x9d, 0xaf, 0x09, 0x64, 0xbe, 0xf5, 0xce, 0x61, 0xf7, 0x9e, 0x8a, 0x76, 0x21,
	0x10, 0xa1, 0x2f, 0x39, 0xe5, 0x42, 0x2a, 0x08, 0x3a, 0x15, 0xc6, 0xbf, 0xc2, 0xde, 0xab, 0x05,
	0x7b, 0x2b, 0x74, 0x9e, 0xb2, 0x11, 0xa7, 0xe8, 0x16, 0x9c, 0x8c, 0xf2, 0x7c, 0x28, 0x8c, 0xe2,
	0x99, 0x51, 0xdc, 0xc0, 0xf7, 0x89, 0x22, 0xdf, 0x8d, 0x44, 0x36, 0x23, 0xe6, 0x52, 0xe6, 0xa4,
	0x59, 0x66, 0x0a, 0x92, 0xd0, 0x0d, 0xa1, 0x56, 0x20, 0x4a, 0xc2, 0x33, 0x9d, 0x19, 0x4f, 0x12,
	0xa2, 0x63, 0xa8, 0x8c, 0xa3, 0x61, 0xae, 0x5b, 0xad, 0x05, 0xf5, 0xa5, 0x9c, 0x9c, 0xe8, 0xe5,
	0x95, 0x7d, 0x69, 0x79, 0xd7, 0xf0, 0xbf, 0x3d, 0x18, 0xcc, 0x17, 0x26, 0xe5, 0xb7, 0x8b, 0x3a,
	0x01, 0x54, 0xbc, 0x36, 0xa1, 0x8d, 0x61, 0x6b, 0x61, 0xd8, 0xbb, 0x81, 0x2d, 0x42, 0x39, 0x15,
	0x3f, 0xd5, 0x69, 0xc1, 0xf6, 0xf2, 0xfd, 0x26, 0xa5, 0xe0, 0xcd, 0x82, 0x46, 0xb1, 0xd9, 0xde,
	0x63, 0x07, 0x11, 0x68, 0x7c, 0xea, 0x1b, 0x1d, 0x6e, 0x7a, 0x07, 0x65, 0xcc, 0x3d, 0xfa, 0xfa,
	0x99, 0xbc, 0x5f, 0xa8, 0x03, 0xf0, 0x91, 0x1c, 0x61, 0xc3, 0x5f, 0xa9, 0xd2, 0xdd, 0x5f, 0xb3,
	0x59, 0x7c, 0x24, 0x84, 0x3f, 0xc5, 0x58, 0xc8, 0x35, 0xe4, 0x35, 0x5d, 0xb9, 0x07, 0x6b, 0x77,
	0xf3, 0x4f, 0x3d, 0x39, 0xea, 0x77, 0xbb, 0x78, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xeb, 0xe4, 0x16,
	0x8a, 0x87, 0x03, 0x00, 0x00,
}
