// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hrlaggregatorsvc.proto

package hagrpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Status struct {
	Station              string   `protobuf:"bytes,1,opt,name=station,proto3" json:"station,omitempty"`
	Update               string   `protobuf:"bytes,2,opt,name=update,proto3" json:"update,omitempty"`
	Temperature          float64  `protobuf:"fixed64,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_hrlaggregatorsvc_b564125bce6068bd, []int{0}
}
func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (dst *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(dst, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetStation() string {
	if m != nil {
		return m.Station
	}
	return ""
}

func (m *Status) GetUpdate() string {
	if m != nil {
		return m.Update
	}
	return ""
}

func (m *Status) GetTemperature() float64 {
	if m != nil {
		return m.Temperature
	}
	return 0
}

type GetStatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatusRequest) Reset()         { *m = GetStatusRequest{} }
func (m *GetStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetStatusRequest) ProtoMessage()    {}
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hrlaggregatorsvc_b564125bce6068bd, []int{1}
}
func (m *GetStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatusRequest.Unmarshal(m, b)
}
func (m *GetStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatusRequest.Marshal(b, m, deterministic)
}
func (dst *GetStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatusRequest.Merge(dst, src)
}
func (m *GetStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetStatusRequest.Size(m)
}
func (m *GetStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatusRequest proto.InternalMessageInfo

type GetStatusResponse struct {
	Status               []*Status `protobuf:"bytes,1,rep,name=status,proto3" json:"status,omitempty"`
	Err                  string    `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetStatusResponse) Reset()         { *m = GetStatusResponse{} }
func (m *GetStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetStatusResponse) ProtoMessage()    {}
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_hrlaggregatorsvc_b564125bce6068bd, []int{2}
}
func (m *GetStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatusResponse.Unmarshal(m, b)
}
func (m *GetStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatusResponse.Marshal(b, m, deterministic)
}
func (dst *GetStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatusResponse.Merge(dst, src)
}
func (m *GetStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetStatusResponse.Size(m)
}
func (m *GetStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatusResponse proto.InternalMessageInfo

func (m *GetStatusResponse) GetStatus() []*Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetStatusResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*Status)(nil), "hagrpc.Status")
	proto.RegisterType((*GetStatusRequest)(nil), "hagrpc.GetStatusRequest")
	proto.RegisterType((*GetStatusResponse)(nil), "hagrpc.GetStatusResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HrlAggregatorSVCClient is the client API for HrlAggregatorSVC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HrlAggregatorSVCClient interface {
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
}

type hrlAggregatorSVCClient struct {
	cc *grpc.ClientConn
}

func NewHrlAggregatorSVCClient(cc *grpc.ClientConn) HrlAggregatorSVCClient {
	return &hrlAggregatorSVCClient{cc}
}

func (c *hrlAggregatorSVCClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, "/hagrpc.HrlAggregatorSVC/GetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HrlAggregatorSVCServer is the server API for HrlAggregatorSVC service.
type HrlAggregatorSVCServer interface {
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
}

func RegisterHrlAggregatorSVCServer(s *grpc.Server, srv HrlAggregatorSVCServer) {
	s.RegisterService(&_HrlAggregatorSVC_serviceDesc, srv)
}

func _HrlAggregatorSVC_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HrlAggregatorSVCServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hagrpc.HrlAggregatorSVC/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HrlAggregatorSVCServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HrlAggregatorSVC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hagrpc.HrlAggregatorSVC",
	HandlerType: (*HrlAggregatorSVCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _HrlAggregatorSVC_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hrlaggregatorsvc.proto",
}

func init() {
	proto.RegisterFile("hrlaggregatorsvc.proto", fileDescriptor_hrlaggregatorsvc_b564125bce6068bd)
}

var fileDescriptor_hrlaggregatorsvc_b564125bce6068bd = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x8d, 0x0b, 0x91, 0x4e, 0x41, 0xd6, 0x39, 0x94, 0xe8, 0x29, 0xe4, 0x20, 0x7b, 0xda,
	0x43, 0xfd, 0x05, 0xea, 0x41, 0x2f, 0x5e, 0xb6, 0xd0, 0x93, 0x97, 0x58, 0x87, 0x54, 0xa8, 0x4d,
	0x9c, 0x4c, 0xfc, 0xfd, 0xe2, 0x6e, 0x5a, 0x8a, 0x78, 0xcb, 0x7b, 0x2f, 0xcc, 0xfb, 0x66, 0x60,
	0xb1, 0xe5, 0x9d, 0x0f, 0x81, 0x29, 0x78, 0x89, 0x9c, 0xbf, 0x37, 0x7d, 0xe2, 0x28, 0x11, 0xf5,
	0xd6, 0x07, 0x4e, 0x1b, 0xf7, 0x0a, 0x7a, 0x25, 0x5e, 0x4a, 0x46, 0x03, 0x17, 0x59, 0xbc, 0x7c,
	0xc4, 0xbd, 0x51, 0x56, 0x75, 0xb3, 0xe1, 0x20, 0x71, 0x01, 0xba, 0xa4, 0x77, 0x2f, 0x64, 0xce,
	0xc7, 0xa0, 0x2a, 0xb4, 0x30, 0x17, 0xfa, 0x4c, 0xc4, 0x5e, 0x0a, 0x93, 0x69, 0xac, 0xea, 0xd4,
	0x70, 0x6a, 0x39, 0x84, 0xf6, 0x89, 0x64, 0x2a, 0x18, 0xe8, 0xab, 0x50, 0x16, 0xf7, 0x02, 0x57,
	0x27, 0x5e, 0x4e, 0x71, 0x9f, 0x09, 0x6f, 0x41, 0xe7, 0xd1, 0x31, 0xca, 0x36, 0xdd, 0x7c, 0x79,
	0xd9, 0x4f, 0x7c, 0x7d, 0xfd, 0x57, 0x53, 0x6c, 0xa1, 0x21, 0xe6, 0xca, 0xf1, 0xfb, 0x5c, 0xae,
	0xa1, 0x7d, 0xe6, 0xdd, 0xfd, 0x71, 0xc5, 0xd5, 0xfa, 0x11, 0x1f, 0x60, 0x76, 0xac, 0x40, 0x73,
	0x18, 0xf5, 0x97, 0xe4, 0xe6, 0xfa, 0x9f, 0x64, 0xe2, 0x71, 0x67, 0x6f, 0x7a, 0xbc, 0xd3, 0xdd,
	0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe9, 0x6d, 0xbd, 0x26, 0x41, 0x01, 0x00, 0x00,
}
