// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.17.3
// source: weatherbitsvc.proto

package weatherbitgrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WeatherbitSVC_GetPeriod_FullMethodName       = "/weatherbitgrpc.WeatherbitSVC/GetPeriod"
	WeatherbitSVC_GetWBPeriod_FullMethodName     = "/weatherbitgrpc.WeatherbitSVC/GetWBPeriod"
	WeatherbitSVC_PushWBPeriod_FullMethodName    = "/weatherbitgrpc.WeatherbitSVC/PushWBPeriod"
	WeatherbitSVC_GetUpdateDate_FullMethodName   = "/weatherbitgrpc.WeatherbitSVC/GetUpdateDate"
	WeatherbitSVC_GetStationsList_FullMethodName = "/weatherbitgrpc.WeatherbitSVC/GetStationsList"
	WeatherbitSVC_GetAverage_FullMethodName      = "/weatherbitgrpc.WeatherbitSVC/GetAverage"
)

// WeatherbitSVCClient is the client API for WeatherbitSVC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WeatherbitSVCClient interface {
	GetPeriod(ctx context.Context, in *GetPeriodRequest, opts ...grpc.CallOption) (*GetPeriodResponse, error)
	GetWBPeriod(ctx context.Context, in *GetWBPeriodRequest, opts ...grpc.CallOption) (*GetWBPeriodResponse, error)
	PushWBPeriod(ctx context.Context, in *PushWBPeriodRequest, opts ...grpc.CallOption) (*PushWBPeriodResponse, error)
	GetUpdateDate(ctx context.Context, in *GetUpdateDateRequest, opts ...grpc.CallOption) (*GetUpdateDateResponse, error)
	GetStationsList(ctx context.Context, in *GetStationsListRequest, opts ...grpc.CallOption) (*GetStationsListResponse, error)
	GetAverage(ctx context.Context, in *GetAverageRequest, opts ...grpc.CallOption) (*GetAverageResponse, error)
}

type weatherbitSVCClient struct {
	cc grpc.ClientConnInterface
}

func NewWeatherbitSVCClient(cc grpc.ClientConnInterface) WeatherbitSVCClient {
	return &weatherbitSVCClient{cc}
}

func (c *weatherbitSVCClient) GetPeriod(ctx context.Context, in *GetPeriodRequest, opts ...grpc.CallOption) (*GetPeriodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPeriodResponse)
	err := c.cc.Invoke(ctx, WeatherbitSVC_GetPeriod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weatherbitSVCClient) GetWBPeriod(ctx context.Context, in *GetWBPeriodRequest, opts ...grpc.CallOption) (*GetWBPeriodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWBPeriodResponse)
	err := c.cc.Invoke(ctx, WeatherbitSVC_GetWBPeriod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weatherbitSVCClient) PushWBPeriod(ctx context.Context, in *PushWBPeriodRequest, opts ...grpc.CallOption) (*PushWBPeriodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushWBPeriodResponse)
	err := c.cc.Invoke(ctx, WeatherbitSVC_PushWBPeriod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weatherbitSVCClient) GetUpdateDate(ctx context.Context, in *GetUpdateDateRequest, opts ...grpc.CallOption) (*GetUpdateDateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUpdateDateResponse)
	err := c.cc.Invoke(ctx, WeatherbitSVC_GetUpdateDate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weatherbitSVCClient) GetStationsList(ctx context.Context, in *GetStationsListRequest, opts ...grpc.CallOption) (*GetStationsListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStationsListResponse)
	err := c.cc.Invoke(ctx, WeatherbitSVC_GetStationsList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weatherbitSVCClient) GetAverage(ctx context.Context, in *GetAverageRequest, opts ...grpc.CallOption) (*GetAverageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAverageResponse)
	err := c.cc.Invoke(ctx, WeatherbitSVC_GetAverage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WeatherbitSVCServer is the server API for WeatherbitSVC service.
// All implementations should embed UnimplementedWeatherbitSVCServer
// for forward compatibility.
type WeatherbitSVCServer interface {
	GetPeriod(context.Context, *GetPeriodRequest) (*GetPeriodResponse, error)
	GetWBPeriod(context.Context, *GetWBPeriodRequest) (*GetWBPeriodResponse, error)
	PushWBPeriod(context.Context, *PushWBPeriodRequest) (*PushWBPeriodResponse, error)
	GetUpdateDate(context.Context, *GetUpdateDateRequest) (*GetUpdateDateResponse, error)
	GetStationsList(context.Context, *GetStationsListRequest) (*GetStationsListResponse, error)
	GetAverage(context.Context, *GetAverageRequest) (*GetAverageResponse, error)
}

// UnimplementedWeatherbitSVCServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWeatherbitSVCServer struct{}

func (UnimplementedWeatherbitSVCServer) GetPeriod(context.Context, *GetPeriodRequest) (*GetPeriodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPeriod not implemented")
}
func (UnimplementedWeatherbitSVCServer) GetWBPeriod(context.Context, *GetWBPeriodRequest) (*GetWBPeriodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWBPeriod not implemented")
}
func (UnimplementedWeatherbitSVCServer) PushWBPeriod(context.Context, *PushWBPeriodRequest) (*PushWBPeriodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushWBPeriod not implemented")
}
func (UnimplementedWeatherbitSVCServer) GetUpdateDate(context.Context, *GetUpdateDateRequest) (*GetUpdateDateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUpdateDate not implemented")
}
func (UnimplementedWeatherbitSVCServer) GetStationsList(context.Context, *GetStationsListRequest) (*GetStationsListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStationsList not implemented")
}
func (UnimplementedWeatherbitSVCServer) GetAverage(context.Context, *GetAverageRequest) (*GetAverageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAverage not implemented")
}
func (UnimplementedWeatherbitSVCServer) testEmbeddedByValue() {}

// UnsafeWeatherbitSVCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WeatherbitSVCServer will
// result in compilation errors.
type UnsafeWeatherbitSVCServer interface {
	mustEmbedUnimplementedWeatherbitSVCServer()
}

func RegisterWeatherbitSVCServer(s grpc.ServiceRegistrar, srv WeatherbitSVCServer) {
	// If the following call pancis, it indicates UnimplementedWeatherbitSVCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WeatherbitSVC_ServiceDesc, srv)
}

func _WeatherbitSVC_GetPeriod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPeriodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeatherbitSVCServer).GetPeriod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeatherbitSVC_GetPeriod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeatherbitSVCServer).GetPeriod(ctx, req.(*GetPeriodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeatherbitSVC_GetWBPeriod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWBPeriodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeatherbitSVCServer).GetWBPeriod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeatherbitSVC_GetWBPeriod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeatherbitSVCServer).GetWBPeriod(ctx, req.(*GetWBPeriodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeatherbitSVC_PushWBPeriod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushWBPeriodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeatherbitSVCServer).PushWBPeriod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeatherbitSVC_PushWBPeriod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeatherbitSVCServer).PushWBPeriod(ctx, req.(*PushWBPeriodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeatherbitSVC_GetUpdateDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUpdateDateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeatherbitSVCServer).GetUpdateDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeatherbitSVC_GetUpdateDate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeatherbitSVCServer).GetUpdateDate(ctx, req.(*GetUpdateDateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeatherbitSVC_GetStationsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStationsListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeatherbitSVCServer).GetStationsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeatherbitSVC_GetStationsList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeatherbitSVCServer).GetStationsList(ctx, req.(*GetStationsListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeatherbitSVC_GetAverage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAverageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeatherbitSVCServer).GetAverage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeatherbitSVC_GetAverage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeatherbitSVCServer).GetAverage(ctx, req.(*GetAverageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WeatherbitSVC_ServiceDesc is the grpc.ServiceDesc for WeatherbitSVC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WeatherbitSVC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weatherbitgrpc.WeatherbitSVC",
	HandlerType: (*WeatherbitSVCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPeriod",
			Handler:    _WeatherbitSVC_GetPeriod_Handler,
		},
		{
			MethodName: "GetWBPeriod",
			Handler:    _WeatherbitSVC_GetWBPeriod_Handler,
		},
		{
			MethodName: "PushWBPeriod",
			Handler:    _WeatherbitSVC_PushWBPeriod_Handler,
		},
		{
			MethodName: "GetUpdateDate",
			Handler:    _WeatherbitSVC_GetUpdateDate_Handler,
		},
		{
			MethodName: "GetStationsList",
			Handler:    _WeatherbitSVC_GetStationsList_Handler,
		},
		{
			MethodName: "GetAverage",
			Handler:    _WeatherbitSVC_GetAverage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "weatherbitsvc.proto",
}
