// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alertssvc.proto

package grpcalt

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Alert struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Desc                 string            `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Params               map[string]string `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Alert) Reset()         { *m = Alert{} }
func (m *Alert) String() string { return proto.CompactTextString(m) }
func (*Alert) ProtoMessage()    {}
func (*Alert) Descriptor() ([]byte, []int) {
	return fileDescriptor_alertssvc_b2d1f6c14ca95569, []int{0}
}
func (m *Alert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Alert.Unmarshal(m, b)
}
func (m *Alert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Alert.Marshal(b, m, deterministic)
}
func (dst *Alert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Alert.Merge(dst, src)
}
func (m *Alert) XXX_Size() int {
	return xxx_messageInfo_Alert.Size(m)
}
func (m *Alert) XXX_DiscardUnknown() {
	xxx_messageInfo_Alert.DiscardUnknown(m)
}

var xxx_messageInfo_Alert proto.InternalMessageInfo

func (m *Alert) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Alert) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Alert) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

type SendAlertRequest struct {
	Alert                *Alert   `protobuf:"bytes,1,opt,name=alert,proto3" json:"alert,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendAlertRequest) Reset()         { *m = SendAlertRequest{} }
func (m *SendAlertRequest) String() string { return proto.CompactTextString(m) }
func (*SendAlertRequest) ProtoMessage()    {}
func (*SendAlertRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_alertssvc_b2d1f6c14ca95569, []int{1}
}
func (m *SendAlertRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendAlertRequest.Unmarshal(m, b)
}
func (m *SendAlertRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendAlertRequest.Marshal(b, m, deterministic)
}
func (dst *SendAlertRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendAlertRequest.Merge(dst, src)
}
func (m *SendAlertRequest) XXX_Size() int {
	return xxx_messageInfo_SendAlertRequest.Size(m)
}
func (m *SendAlertRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendAlertRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendAlertRequest proto.InternalMessageInfo

func (m *SendAlertRequest) GetAlert() *Alert {
	if m != nil {
		return m.Alert
	}
	return nil
}

type SendAlertResponse struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendAlertResponse) Reset()         { *m = SendAlertResponse{} }
func (m *SendAlertResponse) String() string { return proto.CompactTextString(m) }
func (*SendAlertResponse) ProtoMessage()    {}
func (*SendAlertResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_alertssvc_b2d1f6c14ca95569, []int{2}
}
func (m *SendAlertResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendAlertResponse.Unmarshal(m, b)
}
func (m *SendAlertResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendAlertResponse.Marshal(b, m, deterministic)
}
func (dst *SendAlertResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendAlertResponse.Merge(dst, src)
}
func (m *SendAlertResponse) XXX_Size() int {
	return xxx_messageInfo_SendAlertResponse.Size(m)
}
func (m *SendAlertResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendAlertResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendAlertResponse proto.InternalMessageInfo

func (m *SendAlertResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type Email struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string            `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Params               map[string]string `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Email) Reset()         { *m = Email{} }
func (m *Email) String() string { return proto.CompactTextString(m) }
func (*Email) ProtoMessage()    {}
func (*Email) Descriptor() ([]byte, []int) {
	return fileDescriptor_alertssvc_b2d1f6c14ca95569, []int{3}
}
func (m *Email) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Email.Unmarshal(m, b)
}
func (m *Email) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Email.Marshal(b, m, deterministic)
}
func (dst *Email) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Email.Merge(dst, src)
}
func (m *Email) XXX_Size() int {
	return xxx_messageInfo_Email.Size(m)
}
func (m *Email) XXX_DiscardUnknown() {
	xxx_messageInfo_Email.DiscardUnknown(m)
}

var xxx_messageInfo_Email proto.InternalMessageInfo

func (m *Email) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Email) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Email) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

type SendEmailRequest struct {
	Email                *Email   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendEmailRequest) Reset()         { *m = SendEmailRequest{} }
func (m *SendEmailRequest) String() string { return proto.CompactTextString(m) }
func (*SendEmailRequest) ProtoMessage()    {}
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_alertssvc_b2d1f6c14ca95569, []int{4}
}
func (m *SendEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailRequest.Unmarshal(m, b)
}
func (m *SendEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailRequest.Marshal(b, m, deterministic)
}
func (dst *SendEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailRequest.Merge(dst, src)
}
func (m *SendEmailRequest) XXX_Size() int {
	return xxx_messageInfo_SendEmailRequest.Size(m)
}
func (m *SendEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailRequest proto.InternalMessageInfo

func (m *SendEmailRequest) GetEmail() *Email {
	if m != nil {
		return m.Email
	}
	return nil
}

type SendEmailResponse struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendEmailResponse) Reset()         { *m = SendEmailResponse{} }
func (m *SendEmailResponse) String() string { return proto.CompactTextString(m) }
func (*SendEmailResponse) ProtoMessage()    {}
func (*SendEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_alertssvc_b2d1f6c14ca95569, []int{5}
}
func (m *SendEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailResponse.Unmarshal(m, b)
}
func (m *SendEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailResponse.Marshal(b, m, deterministic)
}
func (dst *SendEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailResponse.Merge(dst, src)
}
func (m *SendEmailResponse) XXX_Size() int {
	return xxx_messageInfo_SendEmailResponse.Size(m)
}
func (m *SendEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailResponse proto.InternalMessageInfo

func (m *SendEmailResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*Alert)(nil), "grpcalt.Alert")
	proto.RegisterMapType((map[string]string)(nil), "grpcalt.Alert.ParamsEntry")
	proto.RegisterType((*SendAlertRequest)(nil), "grpcalt.SendAlertRequest")
	proto.RegisterType((*SendAlertResponse)(nil), "grpcalt.SendAlertResponse")
	proto.RegisterType((*Email)(nil), "grpcalt.Email")
	proto.RegisterMapType((map[string]string)(nil), "grpcalt.Email.ParamsEntry")
	proto.RegisterType((*SendEmailRequest)(nil), "grpcalt.SendEmailRequest")
	proto.RegisterType((*SendEmailResponse)(nil), "grpcalt.SendEmailResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AlertSVCClient is the client API for AlertSVC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AlertSVCClient interface {
	SendAlert(ctx context.Context, in *SendAlertRequest, opts ...grpc.CallOption) (*SendAlertResponse, error)
	SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error)
}

type alertSVCClient struct {
	cc *grpc.ClientConn
}

func NewAlertSVCClient(cc *grpc.ClientConn) AlertSVCClient {
	return &alertSVCClient{cc}
}

func (c *alertSVCClient) SendAlert(ctx context.Context, in *SendAlertRequest, opts ...grpc.CallOption) (*SendAlertResponse, error) {
	out := new(SendAlertResponse)
	err := c.cc.Invoke(ctx, "/grpcalt.AlertSVC/SendAlert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertSVCClient) SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error) {
	out := new(SendEmailResponse)
	err := c.cc.Invoke(ctx, "/grpcalt.AlertSVC/SendEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlertSVCServer is the server API for AlertSVC service.
type AlertSVCServer interface {
	SendAlert(context.Context, *SendAlertRequest) (*SendAlertResponse, error)
	SendEmail(context.Context, *SendEmailRequest) (*SendEmailResponse, error)
}

func RegisterAlertSVCServer(s *grpc.Server, srv AlertSVCServer) {
	s.RegisterService(&_AlertSVC_serviceDesc, srv)
}

func _AlertSVC_SendAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertSVCServer).SendAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcalt.AlertSVC/SendAlert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertSVCServer).SendAlert(ctx, req.(*SendAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertSVC_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertSVCServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcalt.AlertSVC/SendEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertSVCServer).SendEmail(ctx, req.(*SendEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AlertSVC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcalt.AlertSVC",
	HandlerType: (*AlertSVCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendAlert",
			Handler:    _AlertSVC_SendAlert_Handler,
		},
		{
			MethodName: "SendEmail",
			Handler:    _AlertSVC_SendEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "alertssvc.proto",
}

func init() { proto.RegisterFile("alertssvc.proto", fileDescriptor_alertssvc_b2d1f6c14ca95569) }

var fileDescriptor_alertssvc_b2d1f6c14ca95569 = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0x87, 0xeb, 0x86, 0x14, 0x7a, 0x91, 0xa0, 0x58, 0x1d, 0x42, 0xa6, 0xca, 0x02, 0xa9, 0x53,
	0x86, 0xb0, 0x14, 0x36, 0x04, 0xdd, 0x51, 0x2a, 0xb1, 0x9b, 0xf4, 0x84, 0x10, 0xf9, 0x87, 0x9d,
	0x56, 0xea, 0x8b, 0x30, 0x22, 0x1e, 0x15, 0xf9, 0x9c, 0x54, 0x49, 0x54, 0xd8, 0xba, 0xd9, 0xf7,
	0xb3, 0xbf, 0x3b, 0x7f, 0x09, 0x5c, 0xc8, 0x14, 0x55, 0xa5, 0xf5, 0x36, 0x09, 0x4b, 0x55, 0x54,
	0x05, 0x3f, 0x7d, 0x53, 0x65, 0x22, 0xd3, 0x4a, 0x7c, 0x33, 0x70, 0x1f, 0x4c, 0xc8, 0x39, 0x9c,
	0xe4, 0x32, 0x43, 0x9f, 0xcd, 0xd8, 0x7c, 0x1c, 0xd3, 0xda, 0xd4, 0xd6, 0xa8, 0x13, 0x7f, 0x68,
	0x6b, 0x66, 0xcd, 0x23, 0x18, 0x95, 0x52, 0xc9, 0x4c, 0xfb, 0xce, 0xcc, 0x99, 0x7b, 0x51, 0x10,
	0xd6, 0xac, 0x90, 0x38, 0xe1, 0x33, 0x85, 0xcb, 0xbc, 0x52, 0xbb, 0xb8, 0x3e, 0x19, 0xdc, 0x81,
	0xd7, 0x2a, 0xf3, 0x09, 0x38, 0x1f, 0xb8, 0xab, 0x3b, 0x99, 0x25, 0x9f, 0x82, 0xbb, 0x95, 0xe9,
	0x06, 0xeb, 0x4e, 0x76, 0x73, 0x3f, 0x5c, 0x30, 0xb1, 0x80, 0xc9, 0x0a, 0xf3, 0x35, 0xb1, 0x63,
	0xfc, 0xdc, 0xa0, 0xae, 0xf8, 0x35, 0xb8, 0xf4, 0x20, 0x22, 0x78, 0xd1, 0x79, 0x77, 0x82, 0xd8,
	0x86, 0xe2, 0x06, 0x2e, 0x5b, 0x37, 0x75, 0x59, 0xe4, 0x1a, 0x4d, 0x6b, 0x54, 0xaa, 0x69, 0x8d,
	0x4a, 0x89, 0x1f, 0x06, 0xee, 0x32, 0x93, 0xef, 0xe9, 0x41, 0x03, 0x53, 0x70, 0xd1, 0x84, 0xcd,
	0x60, 0xb4, 0xf9, 0xc7, 0x01, 0x91, 0x8e, 0xe4, 0x80, 0xd8, 0x2d, 0x07, 0x76, 0xb0, 0xbe, 0x03,
	0x7b, 0xca, 0x86, 0x8d, 0x83, 0xfa, 0xe6, 0x5f, 0x0e, 0xa2, 0x2f, 0x06, 0x67, 0xe4, 0x69, 0xf5,
	0xf2, 0xc8, 0x9f, 0x60, 0xbc, 0xf7, 0xc6, 0xaf, 0xf6, 0xdc, 0xfe, 0x57, 0x08, 0x82, 0x43, 0x91,
	0x6d, 0x21, 0x06, 0x0d, 0xc5, 0x9a, 0xed, 0x52, 0xda, 0xef, 0xe8, 0x51, 0x3a, 0x83, 0x8a, 0xc1,
	0xeb, 0x88, 0x7e, 0xd7, 0xdb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x18, 0x23, 0xc1, 0x27, 0xc1,
	0x02, 0x00, 0x00,
}
