// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stationssvc.proto

package grpc

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Station struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Timezone             string   `protobuf:"bytes,3,opt,name=timezone,proto3" json:"timezone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Station) Reset()         { *m = Station{} }
func (m *Station) String() string { return proto.CompactTextString(m) }
func (*Station) ProtoMessage()    {}
func (*Station) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c93ba665256e54c, []int{0}
}

func (m *Station) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Station.Unmarshal(m, b)
}
func (m *Station) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Station.Marshal(b, m, deterministic)
}
func (m *Station) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Station.Merge(m, src)
}
func (m *Station) XXX_Size() int {
	return xxx_messageInfo_Station.Size(m)
}
func (m *Station) XXX_DiscardUnknown() {
	xxx_messageInfo_Station.DiscardUnknown(m)
}

var xxx_messageInfo_Station proto.InternalMessageInfo

func (m *Station) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Station) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Station) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

type GetStationsRequest struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStationsRequest) Reset()         { *m = GetStationsRequest{} }
func (m *GetStationsRequest) String() string { return proto.CompactTextString(m) }
func (*GetStationsRequest) ProtoMessage()    {}
func (*GetStationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c93ba665256e54c, []int{1}
}

func (m *GetStationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStationsRequest.Unmarshal(m, b)
}
func (m *GetStationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStationsRequest.Marshal(b, m, deterministic)
}
func (m *GetStationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStationsRequest.Merge(m, src)
}
func (m *GetStationsRequest) XXX_Size() int {
	return xxx_messageInfo_GetStationsRequest.Size(m)
}
func (m *GetStationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStationsRequest proto.InternalMessageInfo

func (m *GetStationsRequest) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type GetStationsResponse struct {
	Sts                  map[string]*Station `protobuf:"bytes,1,rep,name=sts,proto3" json:"sts,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Err                  string              `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetStationsResponse) Reset()         { *m = GetStationsResponse{} }
func (m *GetStationsResponse) String() string { return proto.CompactTextString(m) }
func (*GetStationsResponse) ProtoMessage()    {}
func (*GetStationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c93ba665256e54c, []int{2}
}

func (m *GetStationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStationsResponse.Unmarshal(m, b)
}
func (m *GetStationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStationsResponse.Marshal(b, m, deterministic)
}
func (m *GetStationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStationsResponse.Merge(m, src)
}
func (m *GetStationsResponse) XXX_Size() int {
	return xxx_messageInfo_GetStationsResponse.Size(m)
}
func (m *GetStationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStationsResponse proto.InternalMessageInfo

func (m *GetStationsResponse) GetSts() map[string]*Station {
	if m != nil {
		return m.Sts
	}
	return nil
}

func (m *GetStationsResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type GetAllStationsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllStationsRequest) Reset()         { *m = GetAllStationsRequest{} }
func (m *GetAllStationsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllStationsRequest) ProtoMessage()    {}
func (*GetAllStationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c93ba665256e54c, []int{3}
}

func (m *GetAllStationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllStationsRequest.Unmarshal(m, b)
}
func (m *GetAllStationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllStationsRequest.Marshal(b, m, deterministic)
}
func (m *GetAllStationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllStationsRequest.Merge(m, src)
}
func (m *GetAllStationsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllStationsRequest.Size(m)
}
func (m *GetAllStationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllStationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllStationsRequest proto.InternalMessageInfo

type GetAllStationsResponse struct {
	Sts                  map[string]*Station `protobuf:"bytes,1,rep,name=sts,proto3" json:"sts,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Err                  string              `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetAllStationsResponse) Reset()         { *m = GetAllStationsResponse{} }
func (m *GetAllStationsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllStationsResponse) ProtoMessage()    {}
func (*GetAllStationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c93ba665256e54c, []int{4}
}

func (m *GetAllStationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllStationsResponse.Unmarshal(m, b)
}
func (m *GetAllStationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllStationsResponse.Marshal(b, m, deterministic)
}
func (m *GetAllStationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllStationsResponse.Merge(m, src)
}
func (m *GetAllStationsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllStationsResponse.Size(m)
}
func (m *GetAllStationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllStationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllStationsResponse proto.InternalMessageInfo

func (m *GetAllStationsResponse) GetSts() map[string]*Station {
	if m != nil {
		return m.Sts
	}
	return nil
}

func (m *GetAllStationsResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type AddStationsRequest struct {
	Sts                  []*Station `protobuf:"bytes,1,rep,name=sts,proto3" json:"sts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AddStationsRequest) Reset()         { *m = AddStationsRequest{} }
func (m *AddStationsRequest) String() string { return proto.CompactTextString(m) }
func (*AddStationsRequest) ProtoMessage()    {}
func (*AddStationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c93ba665256e54c, []int{5}
}

func (m *AddStationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddStationsRequest.Unmarshal(m, b)
}
func (m *AddStationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddStationsRequest.Marshal(b, m, deterministic)
}
func (m *AddStationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddStationsRequest.Merge(m, src)
}
func (m *AddStationsRequest) XXX_Size() int {
	return xxx_messageInfo_AddStationsRequest.Size(m)
}
func (m *AddStationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddStationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddStationsRequest proto.InternalMessageInfo

func (m *AddStationsRequest) GetSts() []*Station {
	if m != nil {
		return m.Sts
	}
	return nil
}

type AddStationsResponse struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddStationsResponse) Reset()         { *m = AddStationsResponse{} }
func (m *AddStationsResponse) String() string { return proto.CompactTextString(m) }
func (*AddStationsResponse) ProtoMessage()    {}
func (*AddStationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c93ba665256e54c, []int{6}
}

func (m *AddStationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddStationsResponse.Unmarshal(m, b)
}
func (m *AddStationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddStationsResponse.Marshal(b, m, deterministic)
}
func (m *AddStationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddStationsResponse.Merge(m, src)
}
func (m *AddStationsResponse) XXX_Size() int {
	return xxx_messageInfo_AddStationsResponse.Size(m)
}
func (m *AddStationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddStationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddStationsResponse proto.InternalMessageInfo

func (m *AddStationsResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*Station)(nil), "grpc.Station")
	proto.RegisterType((*GetStationsRequest)(nil), "grpc.GetStationsRequest")
	proto.RegisterType((*GetStationsResponse)(nil), "grpc.GetStationsResponse")
	proto.RegisterMapType((map[string]*Station)(nil), "grpc.GetStationsResponse.StsEntry")
	proto.RegisterType((*GetAllStationsRequest)(nil), "grpc.GetAllStationsRequest")
	proto.RegisterType((*GetAllStationsResponse)(nil), "grpc.GetAllStationsResponse")
	proto.RegisterMapType((map[string]*Station)(nil), "grpc.GetAllStationsResponse.StsEntry")
	proto.RegisterType((*AddStationsRequest)(nil), "grpc.AddStationsRequest")
	proto.RegisterType((*AddStationsResponse)(nil), "grpc.AddStationsResponse")
}

func init() { proto.RegisterFile("stationssvc.proto", fileDescriptor_2c93ba665256e54c) }

var fileDescriptor_2c93ba665256e54c = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x93, 0x41, 0x4f, 0xe2, 0x40,
	0x14, 0xc7, 0x3b, 0x2d, 0xbb, 0x0b, 0x8f, 0x2c, 0xd9, 0x1d, 0xb2, 0x6c, 0xb7, 0x6b, 0x02, 0x19,
	0x63, 0xe4, 0xa0, 0x25, 0x41, 0x8d, 0xc6, 0x1b, 0x2a, 0x21, 0x1e, 0xbc, 0x94, 0xc4, 0x3b, 0xd0,
	0xb1, 0x36, 0x42, 0x07, 0x3b, 0x53, 0x12, 0xfc, 0x3c, 0x9e, 0xfc, 0x24, 0x7e, 0x0a, 0xaf, 0x7e,
	0x0d, 0x33, 0xd3, 0x81, 0x94, 0x5a, 0x3d, 0x7a, 0x7b, 0xf3, 0xde, 0xff, 0xbd, 0xfe, 0x7f, 0xef,
	0xa5, 0xf0, 0x9b, 0x8b, 0x91, 0x08, 0x59, 0xc4, 0xf9, 0x62, 0xe2, 0xce, 0x63, 0x26, 0x18, 0x2e,
	0x05, 0xf1, 0x7c, 0xe2, 0xec, 0x07, 0xa1, 0xb8, 0x4d, 0xc6, 0xee, 0x84, 0xcd, 0x3a, 0x01, 0x0b,
	0x58, 0x47, 0x15, 0xc7, 0xc9, 0x8d, 0x7a, 0xa9, 0x87, 0x8a, 0xd2, 0x26, 0x72, 0x09, 0x3f, 0x86,
	0xe9, 0x24, 0x5c, 0x03, 0x33, 0xf4, 0x6d, 0xd4, 0x42, 0xed, 0x8a, 0x67, 0x86, 0x3e, 0xc6, 0x50,
	0x8a, 0x46, 0x33, 0x6a, 0x9b, 0x2a, 0xa3, 0x62, 0xec, 0x40, 0x59, 0x84, 0x33, 0xfa, 0xc0, 0x22,
	0x6a, 0x5b, 0x2a, 0xbf, 0x7e, 0x93, 0x3d, 0xc0, 0x03, 0x2a, 0xf4, 0x34, 0xee, 0xd1, 0xfb, 0x84,
	0x72, 0x81, 0x1b, 0x60, 0x85, 0x3e, 0xb7, 0x51, 0xcb, 0x6a, 0x57, 0xce, 0x4a, 0xcf, 0x2f, 0x4d,
	0xc3, 0x93, 0x09, 0xf2, 0x88, 0xa0, 0xbe, 0x21, 0xe7, 0x73, 0x16, 0x71, 0x8a, 0x0f, 0xc1, 0xe2,
	0x22, 0xd5, 0x57, 0xbb, 0xc4, 0x95, 0x4c, 0x6e, 0x81, 0xce, 0x1d, 0x0a, 0xde, 0x8f, 0x44, 0xbc,
	0xf4, 0xa4, 0x1c, 0xff, 0x02, 0x8b, 0xc6, 0xb1, 0xb6, 0x2a, 0x43, 0xa7, 0x0f, 0xe5, 0x95, 0x44,
	0x56, 0xef, 0xe8, 0x52, 0xa3, 0xc9, 0x10, 0x6f, 0xc3, 0xb7, 0xc5, 0x68, 0x9a, 0xa4, 0x70, 0xd5,
	0xee, 0xcf, 0xf4, 0x3b, 0xfa, 0x23, 0x5e, 0x5a, 0x3b, 0x35, 0x4f, 0x10, 0xf9, 0x0b, 0x7f, 0x06,
	0x54, 0xf4, 0xa6, 0xd3, 0x1c, 0x17, 0x79, 0x42, 0xd0, 0xc8, 0x57, 0x34, 0xc2, 0x71, 0x16, 0x61,
	0x67, 0x8d, 0x50, 0x20, 0xfd, 0x2a, 0x8a, 0x23, 0xc0, 0x3d, 0xdf, 0xcf, 0x9f, 0xa6, 0x99, 0xf5,
	0x99, 0x6b, 0x96, 0x15, 0xb2, 0x0b, 0xf5, 0x8d, 0x36, 0xcd, 0xa7, 0x6d, 0xa2, 0xb5, 0xcd, 0xee,
	0x2b, 0x02, 0xd0, 0xb2, 0xe1, 0xf5, 0x39, 0xbe, 0x80, 0x6a, 0xe6, 0x64, 0xd8, 0x2e, 0xb8, 0xa2,
	0x72, 0xe0, 0xfc, 0xfb, 0xf0, 0xbe, 0xc4, 0xc0, 0x57, 0x50, 0xdb, 0xdc, 0x1a, 0xfe, 0x5f, 0xbc,
	0xcb, 0x74, 0xd6, 0xd6, 0x67, 0x8b, 0x26, 0x86, 0x34, 0x95, 0x81, 0x59, 0x99, 0x7a, 0xbf, 0x96,
	0x95, 0xa9, 0x02, 0x72, 0x62, 0x8c, 0xbf, 0xab, 0xdf, 0xe6, 0xe0, 0x2d, 0x00, 0x00, 0xff, 0xff,
	0x1f, 0xf9, 0x6e, 0x4c, 0x80, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StationSVCClient is the client API for StationSVC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StationSVCClient interface {
	GetStations(ctx context.Context, in *GetStationsRequest, opts ...grpc.CallOption) (*GetStationsResponse, error)
	GetAllStations(ctx context.Context, in *GetAllStationsRequest, opts ...grpc.CallOption) (*GetAllStationsResponse, error)
	AddStations(ctx context.Context, in *AddStationsRequest, opts ...grpc.CallOption) (*AddStationsResponse, error)
}

type stationSVCClient struct {
	cc *grpc.ClientConn
}

func NewStationSVCClient(cc *grpc.ClientConn) StationSVCClient {
	return &stationSVCClient{cc}
}

func (c *stationSVCClient) GetStations(ctx context.Context, in *GetStationsRequest, opts ...grpc.CallOption) (*GetStationsResponse, error) {
	out := new(GetStationsResponse)
	err := c.cc.Invoke(ctx, "/grpc.StationSVC/GetStations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stationSVCClient) GetAllStations(ctx context.Context, in *GetAllStationsRequest, opts ...grpc.CallOption) (*GetAllStationsResponse, error) {
	out := new(GetAllStationsResponse)
	err := c.cc.Invoke(ctx, "/grpc.StationSVC/GetAllStations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stationSVCClient) AddStations(ctx context.Context, in *AddStationsRequest, opts ...grpc.CallOption) (*AddStationsResponse, error) {
	out := new(AddStationsResponse)
	err := c.cc.Invoke(ctx, "/grpc.StationSVC/AddStations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StationSVCServer is the server API for StationSVC service.
type StationSVCServer interface {
	GetStations(context.Context, *GetStationsRequest) (*GetStationsResponse, error)
	GetAllStations(context.Context, *GetAllStationsRequest) (*GetAllStationsResponse, error)
	AddStations(context.Context, *AddStationsRequest) (*AddStationsResponse, error)
}

// UnimplementedStationSVCServer can be embedded to have forward compatible implementations.
type UnimplementedStationSVCServer struct {
}

func (*UnimplementedStationSVCServer) GetStations(ctx context.Context, req *GetStationsRequest) (*GetStationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStations not implemented")
}
func (*UnimplementedStationSVCServer) GetAllStations(ctx context.Context, req *GetAllStationsRequest) (*GetAllStationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllStations not implemented")
}
func (*UnimplementedStationSVCServer) AddStations(ctx context.Context, req *AddStationsRequest) (*AddStationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddStations not implemented")
}

func RegisterStationSVCServer(s *grpc.Server, srv StationSVCServer) {
	s.RegisterService(&_StationSVC_serviceDesc, srv)
}

func _StationSVC_GetStations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StationSVCServer).GetStations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.StationSVC/GetStations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StationSVCServer).GetStations(ctx, req.(*GetStationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StationSVC_GetAllStations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllStationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StationSVCServer).GetAllStations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.StationSVC/GetAllStations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StationSVCServer).GetAllStations(ctx, req.(*GetAllStationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StationSVC_AddStations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddStationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StationSVCServer).AddStations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.StationSVC/AddStations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StationSVCServer).AddStations(ctx, req.(*AddStationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StationSVC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.StationSVC",
	HandlerType: (*StationSVCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStations",
			Handler:    _StationSVC_GetStations_Handler,
		},
		{
			MethodName: "GetAllStations",
			Handler:    _StationSVC_GetAllStations_Handler,
		},
		{
			MethodName: "AddStations",
			Handler:    _StationSVC_AddStations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stationssvc.proto",
}
